In [2]:
import numpy as np
import pandas as pd

In [3]:
cols = ['Currency','Account Type','Accounting Net Amount',
#'Accounting Net Amount Difference','Accounting Net Amount Difference Absolute ',
'Activity Code','Age','Age WK',
'Asset Type Category','Base Currency','Base Net Amount','Bloomberg_Yellow_Key',
'B-P Net Amount',
#'B-P Net Amount Difference','B-P Net Amount Difference Absolute',
'BreakID',
'Business Date','Cancel Amount','Cancel Flag','CUSIP','Custodian',
'Custodian Account',
'Derived Source','Description','ExpiryDate','ExternalComment1','ExternalComment2',
'ExternalComment3','Fund','FX Rate','Interest Amount','InternalComment1','InternalComment2',
'InternalComment3','Investment Type','Is Combined Data','ISIN','Keys',
'Mapped Custodian Account','Net Amount Difference','Net Amount Difference Absolute','Non Trade Description',
'OTE Custodian Account',
#'Predicted Action','Predicted Status','Prediction Details',
'Price','Prime Broker',
'Quantity','SEDOL','Settle Date','SPM ID','Status','Strike Price',
'System Comments','Ticker','Trade Date','Trade Expenses','Transaction Category','Transaction ID','Transaction Type',
'Underlying Cusip','Underlying Investment ID','Underlying ISIN','Underlying Sedol','Underlying Ticker','Source Combination','_ID']
#'UnMapped']

add = ['ViewData.Side0_UniqueIds', 'ViewData.Side1_UniqueIds',
      # 'MetaData.0._RecordID','MetaData.1._RecordID',
       'ViewData.Task Business Date']

In [4]:
new_cols = ['ViewData.' + x for x in cols] + add

In [5]:
#df_170.shape

## Read testing data

In [4712]:
#MeoCollections.MEO_HST_RecData_379_2020-06-18
meo = pd.read_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/MEO/MeoCollections.MEO_HST_RecData_125_2020-06-8.csv",usecols=new_cols)

In [232]:
#df['ViewData.Task Business Date']

In [4713]:
meo['ViewData.Status'].value_counts()

OB     8177
SMR    3797
SMT    1493
SDB     219
SPM     174
SMB     171
UDB      79
UMB      70
CMF      12
UOB      11
CNF       8
Name: ViewData.Status, dtype: int64

In [4714]:
df1 = meo[~meo['ViewData.Status'].isin(['SMT','HST', 'OC', 'CT', 'Archive','SMR'])]
#df = df[df['MatchStatus'] != 21]
df1 = df1[~df1['ViewData.Status'].isnull()]
df1 = df1.reset_index()
df1 = df1.drop('index',1)

In [4715]:
#df1[(df1['Date']=='2020-04-10') & (df1['ViewData.Side1_UniqueIds']=='996_125813417_Goldman Sachs')]
df1.shape

(8921, 64)

## Machine generated output

In [4716]:
df = df1.copy()

In [4717]:
df = df.reset_index()
df = df.drop('index',1)

In [4718]:
df.shape

(8921, 64)

In [4719]:
pd.set_option('display.max_columns', 500)

In [4720]:
df['Date'] = pd.to_datetime(df['ViewData.Task Business Date'])

In [4721]:
#df['Date'] = pd.to_datetime(df['ViewData.Task Business Date'])

In [4722]:
df = df[~df['Date'].isnull()]
df = df.reset_index()
df = df.drop('index',1)

In [4723]:
pd.to_datetime(df['Date'])

0      2020-06-09 00:00:00+00:00
1      2020-06-09 00:00:00+00:00
2      2020-06-09 00:00:00+00:00
3      2020-06-09 00:00:00+00:00
4      2020-06-09 00:00:00+00:00
                  ...
8916   2020-06-09 00:00:00+00:00
8917   2020-06-09 00:00:00+00:00
8918   2020-06-09 00:00:00+00:00
8919   2020-06-09 00:00:00+00:00
8920   2020-06-09 00:00:00+00:00
Name: Date, Length: 8921, dtype: datetime64[ns, UTC]

In [4724]:
df['Date'] = pd.to_datetime(df['Date']).dt.date

In [4725]:
df['Date'] = df['Date'].astype(str)

In [4726]:
df['ViewData.Status'].value_counts()

OB     8177
SDB     219
SPM     174
SMB     171
UDB      79
UMB      70
CMF      12
UOB      11
CNF       8
Name: ViewData.Status, dtype: int64

In [4727]:
df = df[df['ViewData.Status'].isin(['OB','SPM','SDB','UOB','UDB','SMB'])]
df = df.reset_index()
df = df.drop('index',1)

In [4728]:
df['ViewData.Side0_UniqueIds'] = df['ViewData.Side0_UniqueIds'].astype(str)
df['ViewData.Side1_UniqueIds'] = df['ViewData.Side1_UniqueIds'].astype(str)
df['flag_side0'] = df.apply(lambda x: len(x['ViewData.Side0_UniqueIds'].split(',')), axis=1)
df['flag_side1'] = df.apply(lambda x: len(x['ViewData.Side1_UniqueIds'].split(',')), axis=1)

In [4729]:
#df_170[(df_170['ViewData.Status']=='UMR')]

In [4730]:
df['Date'].value_counts()

2020-06-09    8713
2020-06-02      18
2020-03-03      14
2020-05-20      10
2020-05-08       8
2020-01-16       8
2020-01-14       8
2020-06-05       6
2020-04-09       4
2020-05-04       4
2020-03-10       4
2020-01-28       4
2020-01-09       4
2020-03-12       4
2020-03-09       4
2020-04-30       2
2020-05-15       2
2020-01-31       2
2020-03-30       2
2020-05-26       2
2020-01-08       2
2020-03-02       2
2020-05-19       2
2020-05-05       2
Name: Date, dtype: int64

## Sample data on one date

In [4731]:
#df = df.rename(columns= {'ViewData.Cust Net Amount':'ViewData.B-P Net Amount'})

In [4944]:
sample = df[df['Date'] =='2020-06-09']
sample = sample.reset_index()
sample = sample.drop('index',1)

In [4945]:
smb = sample[sample['ViewData.Status']=='SMB'].reset_index()
smb = smb.drop('index',1)

In [4946]:
#import glob
#df_list = []

#path = "//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/AUA/*.csv"
#for fname in glob.glob(path):
#    print(fname)
#    if "125" in fname:
#        df_list.append(pd.read_csv(fname))

In [4947]:
#dfff = pd.concat(df_list, axis=0)
#dfff['Date'] = pd.to_datetime(dfff['ViewData.Task Business Date'])
#dfff[dfff['ViewData.Status']=='UCB'].shape

In [4948]:
#dfff[dfff['ViewData.Status']=='UCB'].groupby('Date')['ViewData.Age'].size()

In [4949]:
#dfff[(dfff['ViewData.Status']=='UCB') & (dfff['Date']=='2020-06-30')]['ViewData.Side1_UniqueIds'].nunique()

In [4950]:
smb_pb = smb.copy()
smb_acc = smb.copy()

In [4951]:
smb_pb['ViewData.Accounting Net Amount'] = np.nan
smb_pb['ViewData.Side0_UniqueIds'] = np.nan
smb_pb['ViewData.Status'] ='SMB-OB'

smb_acc['ViewData.B-P Net Amount'] = np.nan
smb_acc['ViewData.Side1_UniqueIds'] = np.nan
smb_acc['ViewData.Status'] ='SMB-OB'

In [4952]:
sample = sample[sample['ViewData.Status']!='SMB']
sample = sample.reset_index()
sample = sample.drop('index',1)

In [4953]:
sample.shape

(8542, 67)

In [4954]:
sample = pd.concat([sample,smb_pb,smb_acc],axis=0)
sample = sample.reset_index()
sample = sample.drop('index',1)

In [4955]:
sample['ViewData.Status'].value_counts()

OB        8059
SMB-OB     342
SDB        219
SPM        174
UDB         79
UOB         11
Name: ViewData.Status, dtype: int64

In [4958]:
sample['ViewData.Side0_UniqueIds'] = sample['ViewData.Side0_UniqueIds'].astype(str)
sample['ViewData.Side1_UniqueIds'] = sample['ViewData.Side1_UniqueIds'].astype(str)

In [4959]:
sample.loc[sample['ViewData.Side0_UniqueIds']=='nan','flag_side0'] = 0
sample.loc[sample['ViewData.Side1_UniqueIds']=='nan','flag_side1'] = 0

In [4960]:
sample['ViewData.Status'].value_counts()

OB        8059
SMB-OB     342
SDB        219
SPM        174
UDB         79
UOB         11
Name: ViewData.Status, dtype: int64

In [4961]:
sample['flag_side1'].value_counts()

1    5152
0    3732
Name: flag_side1, dtype: int64

In [4962]:
sample.loc[sample['ViewData.Side1_UniqueIds']=='nan','Trans_side'] = 'B_side'
sample.loc[sample['ViewData.Side0_UniqueIds']=='nan','Trans_side'] = 'A_side'

sample.loc[sample['Trans_side']=='A_side','ViewData.B-P Currency'] = sample.loc[sample['Trans_side']=='A_side','ViewData.Currency']
sample.loc[sample['Trans_side']=='B_side','ViewData.Accounting Currency'] = sample.loc[sample['Trans_side']=='B_side','ViewData.Currency'] 

sample['ViewData.B-P Currency'] = sample['ViewData.B-P Currency'].astype(str)
sample['ViewData.Accounting Currency'] = sample['ViewData.Accounting Currency'].astype(str)
sample['ViewData.Mapped Custodian Account'] = sample['ViewData.Mapped Custodian Account'].astype(str)
#sample['ViewData.Mapped Custodian Account'] = sample['ViewData.Mapped Custodian Account'].astype(str)
sample['filter_key'] = sample.apply(lambda x: x['ViewData.Mapped Custodian Account'] + x['ViewData.B-P Currency'] if x['Trans_side']=='A_side' else x['ViewData.Mapped Custodian Account'] + x['ViewData.Accounting Currency'], axis=1)


sample1 = sample[(sample['flag_side0']<=1) & (sample['flag_side1']<=1) & (sample['ViewData.Status'].isin(['OB','SPM','SDB','UDB','UOB','SMB-OB']))]

sample1 = sample1.reset_index()
sample1 = sample1.drop('index', 1)

In [4963]:
sample1['ViewData.BreakID'] = sample1['ViewData.BreakID'].astype(int)

In [4964]:
sample1 = sample1[sample1['ViewData.BreakID']!=-1]
sample1 = sample1.reset_index()
sample1 = sample1.drop('index',1)

In [4965]:
sample1 = sample1.sort_values(['ViewData.BreakID','Date'], ascending =[True, False])
sample1 = sample1.reset_index()
sample1 = sample1.drop('index',1)

In [4966]:
sample1['ViewData.Status'].value_counts()

OB        8059
SMB-OB     342
SDB        219
SPM        174
UDB         77
UOB         11
Name: ViewData.Status, dtype: int64

In [5252]:
#sample1[sample1['ViewData.Status']=='SMB-OB']

In [4968]:
aa = sample1[sample1['Trans_side']=='A_side']
bb = sample1[sample1['Trans_side']=='B_side']

In [4969]:
bb['ViewData.Source Combination'].value_counts()

Advent Geneva,Morgan Stanley    2044
Advent Geneva,Goldman Sachs     1363
Advent Geneva,CITI               152
Advent Geneva,UBS                 73
Advent Geneva,State Street        28
Advent Geneva,US BANK             28
Advent Geneva,Northern Trust      20
Advent Geneva,Barclays            16
Advent Geneva,JP Morgan            6
Name: ViewData.Source Combination, dtype: int64

In [4970]:
aa['filter_key'] = aa['ViewData.Source Combination'].astype(str) + aa['ViewData.Mapped Custodian Account'].astype(str) + aa['ViewData.B-P Currency'].astype(str)

bb['filter_key'] = bb['ViewData.Source Combination'].astype(str) + bb['ViewData.Mapped Custodian Account'].astype(str) + bb['ViewData.Accounting Currency'].astype(str)

C:\Users\consultant136\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\consultant136\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [4971]:
aa = aa.reset_index()
aa = aa.drop('index', 1)
bb = bb.reset_index()
bb = bb.drop('index', 1)

In [4972]:
#'ViewData.Side0_UniqueIds', 'ViewData.Side1_UniqueIds'
common_cols = ['ViewData.Accounting Net Amount', 'ViewData.Age',
'ViewData.Age WK', 'ViewData.Asset Type Category',
'ViewData.B-P Net Amount', 'ViewData.Base Net Amount','ViewData.CUSIP', 
 'ViewData.Cancel Amount',
       'ViewData.Cancel Flag',
#'ViewData.Commission',
        'ViewData.Currency', 'ViewData.Custodian',
       'ViewData.Custodian Account',
       'ViewData.Description', 'ViewData.ExpiryDate', 'ViewData.Fund',
       'ViewData.ISIN',
       'ViewData.Investment Type',
      # 'ViewData.Keys',
       'ViewData.Mapped Custodian Account',
       'ViewData.Net Amount Difference',
       'ViewData.Net Amount Difference Absolute',
        #'ViewData.OTE Ticker',
        'ViewData.Price',
       'ViewData.Prime Broker', 'ViewData.Quantity',
       'ViewData.SEDOL', 'ViewData.SPM ID', 'ViewData.Settle Date',
       
  #  'ViewData.Strike Price',
               'Date',
       'ViewData.Ticker', 'ViewData.Trade Date',
       'ViewData.Transaction Category',
       'ViewData.Transaction Type', 'ViewData.Underlying Cusip',
       'ViewData.Underlying ISIN',
       'ViewData.Underlying Sedol','filter_key','ViewData.Status','ViewData.BreakID',
              'ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds','ViewData._ID']

In [4973]:
bb = bb[~bb['ViewData.Accounting Net Amount'].isnull()]
bb = bb.reset_index()
bb = bb.drop('index',1)

In [4974]:
bb['ViewData.Status'].value_counts()

OB        3424
SMB-OB     171
SPM         52
SDB         50
UDB         26
UOB          7
Name: ViewData.Status, dtype: int64

In [4975]:
###################### loop 3 ###############################

from tqdm import tqdm

pool =[]
key_index =[]
training_df =[]

no_pair_ids = []
#max_rows = 5

for d in tqdm(aa['Date'].unique()):
    aa1 = aa.loc[aa['Date']==d,:][common_cols]
    bb1 = bb.loc[bb['Date']==d,:][common_cols]
    
    aa1 = aa1.reset_index()
    aa1 = aa1.drop('index',1)
    bb1 = bb1.reset_index()
    bb1 = bb1.drop('index', 1)
    
    bb1 = bb1.sort_values(by='filter_key',ascending =True)
    
    for key in (list(np.unique(np.array(list(aa1['filter_key'].values) + list(bb1['filter_key'].values))))):
        
        df1 = aa1[aa1['filter_key']==key]
        df2 = bb1[bb1['filter_key']==key]

        if df1.empty == False and df2.empty == False:
            #aa_df = pd.concat([aa1[aa1.index==i]]*repeat_num, ignore_index=True)
            #bb_df = bb1.loc[pool[len(pool)-1],:][common_cols].reset_index()
            #bb_df = bb_df.drop('index', 1)

            df1 = df1.rename(columns={'ViewData.BreakID':'ViewData.BreakID_A_side'})
            df2 = df2.rename(columns={'ViewData.BreakID':'ViewData.BreakID_B_side'})

            #dff  = pd.concat([aa[aa.index==i],bb.loc[pool[i],:][accounting_vars]],axis=1)

            df1 = df1.reset_index()
            df2 = df2.reset_index()
            df1 = df1.drop('index', 1)
            df2 = df2.drop('index', 1)

            df1.columns = ['SideA.' + x  for x in df1.columns] 
            df2.columns = ['SideB.' + x  for x in df2.columns]

            df1 = df1.rename(columns={'SideA.filter_key':'filter_key'})
            df2 = df2.rename(columns={'SideB.filter_key':'filter_key'})

            #dff = pd.concat([aa_df,bb_df],axis=1)
            dff = merge(df1, df2, on='filter_key')
            training_df.append(dff)
                #key_index.append(i)
            #else:
            #no_pair_ids.append([aa1[(aa1['filter_key']=='key') & (aa1['ViewData.Status'].isin(['OB','SDB']))]['ViewData.Side1_UniqueIds'].values[0]])
               # no_pair_ids.append(aa1[(aa1['filter_key']== key) & (aa1['ViewData.Status'].isin(['OB','SDB']))]['ViewData.Side1_UniqueIds'].values[0])
    
        else:
            no_pair_ids.append([aa1[(aa1['filter_key']==key) & (aa1['ViewData.Status'].isin(['OB','SDB']))]['ViewData.Side1_UniqueIds'].values])
            no_pair_ids.append([bb1[(bb1['filter_key']==key) & (bb1['ViewData.Status'].isin(['OB','SDB']))]['ViewData.Side0_UniqueIds'].values])
            

no_pair_ids = np.unique(np.concatenate(no_pair_ids,axis=1)[0])

100%|████████████████████████████████████████████| 1/1 [00:13<00:00, 13.72s/it]

In [4976]:
#no_pair_ids = np.unique(np.concatenate(no_pair_ids,axis=1)[0])

In [4977]:
#pd.DataFrame(no_pair_ids).rename

In [4978]:
len(no_pair_ids)

177

In [4981]:
test_file['SideA.ViewData.Status'].value_counts()

OB        937654
SMB-OB     44295
SDB        40726
SPM        37329
UDB        14088
UOB          765
Name: SideA.ViewData.Status, dtype: int64

In [4980]:
test_file = pd.concat(training_df)

In [4982]:
test_file = test_file.reset_index()
test_file = test_file.drop('index',1)

In [4983]:
test_file['SideB.ViewData.BreakID_B_side'] = test_file['SideB.ViewData.BreakID_B_side'].astype('int64')
test_file['SideA.ViewData.BreakID_A_side'] = test_file['SideA.ViewData.BreakID_A_side'].astype('int64')

In [4984]:
model_cols = [
'SideA.ViewData.Accounting Net Amount', 
'SideA.ViewData.B-P Net Amount', 
'SideA.ViewData.CUSIP', 
'SideA.ViewData.Currency', 
#'SideA.ViewData.Description',
'SideA.ViewData.ISIN', 
'SideB.ViewData.Accounting Net Amount',
'SideB.ViewData.B-P Net Amount',
'SideB.ViewData.CUSIP',
'SideB.ViewData.Currency',
#'SideB.ViewData.Description', 
'SideB.ViewData.ISIN',
'SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 
'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side',
'label']


y_col = ['label']

In [4985]:
test_file['SideB.ViewData.CUSIP'] = test_file['SideB.ViewData.CUSIP'].str.split(".",expand=True)[0]
test_file['SideA.ViewData.CUSIP'] = test_file['SideA.ViewData.CUSIP'].str.split(".",expand=True)[0]

In [4986]:
test_file['SideA.ViewData.ISIN'] = test_file['SideA.ViewData.ISIN'].astype(str)
test_file['SideB.ViewData.ISIN'] = test_file['SideB.ViewData.ISIN'].astype(str)
test_file['SideA.ViewData.CUSIP'] = test_file['SideA.ViewData.CUSIP'].astype(str)
test_file['SideB.ViewData.CUSIP'] = test_file['SideB.ViewData.CUSIP'].astype(str)
test_file['SideA.ViewData.Currency'] = test_file['SideA.ViewData.Currency'].astype(str)
test_file['SideB.ViewData.Currency'] = test_file['SideB.ViewData.Currency'].astype(str)


test_file['SideA.ViewData.Trade Date'] = test_file['SideA.ViewData.Trade Date'].astype(str)
test_file['SideB.ViewData.Trade Date'] = test_file['SideB.ViewData.Trade Date'].astype(str)
test_file['SideA.ViewData.Settle Date'] = test_file['SideA.ViewData.Settle Date'].astype(str)
test_file['SideB.ViewData.Settle Date'] = test_file['SideB.ViewData.Settle Date'].astype(str)
test_file['SideA.ViewData.Fund'] = test_file['SideA.ViewData.Fund'].astype(str)
test_file['SideB.ViewData.Fund'] = test_file['SideB.ViewData.Fund'].astype(str)

In [4987]:
#test_file[['SideA.ViewData.ISIN','SideB.ViewData.ISIN']]

def equals_fun(a,b):
    if a == b:
        return 1
    else:
        return 0

vec_equals_fun = np.vectorize(equals_fun)
values_ISIN_A_Side = test_file['SideA.ViewData.ISIN'].values
values_ISIN_B_Side = test_file['SideB.ViewData.ISIN'].values
#test_file['ISIN_match'] = vec_equals_fun(values_ISIN_A_Side,values_ISIN_B_Side)

values_CUSIP_A_Side = test_file['SideA.ViewData.CUSIP'].values
values_CUSIP_B_Side = test_file['SideB.ViewData.CUSIP'].values
#
# values_CUSIP_A_Side = test_file['SideA.ViewData.Currency'].values
# values_CUSIP_B_Side = test_file['SideB.ViewData.Currency'].values

values_Currency_match_A_Side = test_file['SideA.ViewData.Currency'].values
values_Currency_match_B_Side = test_file['SideA.ViewData.Currency'].values

values_Trade_Date_match_A_Side = test_file['SideA.ViewData.Trade Date'].values
values_Trade_Date_match_B_Side = test_file['SideB.ViewData.Trade Date'].values

values_Settle_Date_match_A_Side = test_file['SideA.ViewData.Settle Date'].values
values_Settle_Date_match_B_Side = test_file['SideB.ViewData.Settle Date'].values

values_Fund_match_A_Side = test_file['SideA.ViewData.Fund'].values
values_Fund_match_B_Side = test_file['SideB.ViewData.Fund'].values

test_file['ISIN_match'] = vec_equals_fun(values_ISIN_A_Side,values_ISIN_B_Side)
test_file['CUSIP_match'] = vec_equals_fun(values_CUSIP_A_Side,values_CUSIP_B_Side)
test_file['Currency_match'] = vec_equals_fun(values_Currency_match_A_Side,values_Currency_match_B_Side)
test_file['Trade_Date_match'] = vec_equals_fun(values_Trade_Date_match_A_Side,values_Trade_Date_match_B_Side)
test_file['Settle_Date_match'] = vec_equals_fun(values_Settle_Date_match_A_Side,values_Settle_Date_match_B_Side)
test_file['Fund_match'] = vec_equals_fun(values_Fund_match_A_Side,values_Fund_match_B_Side)

In [4988]:
#test_file['ISIN_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.ISIN']==x['SideB.ViewData.ISIN'] else 0, axis=1)
#test_file['CUSIP_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.CUSIP']==x['SideB.ViewData.CUSIP'] else 0, axis=1)
#test_file['Currency_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.Currency']==x['SideB.ViewData.Currency'] else 0, axis=1)

In [4989]:
#test_file['Trade_Date_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.Trade Date']==x['SideB.ViewData.Trade Date'] else 0, axis=1)
#test_file['Settle_Date_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.Settle Date']==x['SideB.ViewData.Settle Date'] else 0, axis=1)
#test_file['Fund_match'] = test_file.apply(lambda x: 1 if x['SideA.ViewData.Fund']==x['SideB.ViewData.Fund'] else 0, axis=1)

In [4990]:
test_file['Amount_diff_1'] = test_file['SideA.ViewData.Accounting Net Amount'] - test_file['SideB.ViewData.B-P Net Amount']
test_file['Amount_diff_2'] = test_file['SideB.ViewData.Accounting Net Amount'] - test_file['SideA.ViewData.B-P Net Amount']

In [4991]:
#test_file = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/OakTree/X_test_files_after_loop/meo_testing_HST_RecData_379_06_19_2020_test_file_with_ID.csv')

In [4992]:
#test_file = test_file.drop('Unnamed: 0',1)

In [4993]:
test_file['Trade_date_diff'] = (pd.to_datetime(test_file['SideA.ViewData.Trade Date']) - pd.to_datetime(test_file['SideB.ViewData.Trade Date'])).dt.days

test_file['Settle_date_diff'] = (pd.to_datetime(test_file['SideA.ViewData.Settle Date']) - pd.to_datetime(test_file['SideB.ViewData.Settle Date'])).dt.days

In [4994]:
def mhreplaced(item):
    word1 = []
    word2 = []
    if (type(item) == str):
    
        for items in item.split(' '):
            if (type(items) == str):
                items = items.lower()
                if items.isdigit() == False:
                    word1.append(items)
        
            
                for c in word1:
                    if c.endswith('MH')==False:
                        word2.append(c)
    
                words = ' '.join(word2)
                return words
    else:
        return item
    

def fundmatch(item):
    items = item.lower()
    items = item.replace(' ','') 
    return items

In [4995]:


############ Fund match new ########

values_Fund_match_A_Side = test_file['SideA.ViewData.Fund'].values
values_Fund_match_B_Side = test_file['SideB.ViewData.Fund'].values

vec_fund_match = np.vectorize(fundmatch)

#test_file['ISIN_match'] = vec_(values_ISIN_A_Side,values_ISIN_B_Side)
#test_file['SideA.ViewData.Fund'] = test_file.apply(lambda x : fundmatch(x['SideA.ViewData.Fund']), axis=1)
test_file['SideA.ViewData.Fund'] = vec_fund_match(values_Fund_match_A_Side)
#test_file['SideB.ViewData.Fund'] = test_file.apply(lambda x : fundmatch(x['SideB.ViewData.Fund']), axis=1)
test_file['SideB.ViewData.Fund'] = vec_fund_match(values_Fund_match_B_Side)

In [4996]:
#test_file['SideA.ViewData.Fund']

In [4997]:
#test_file['SideB.ViewData.Transaction Type'] = test_file['SideB.ViewData.Transaction Type'].apply(lambda x : mhreplaced(x))

In [4998]:
#test_file['SideA.ViewData.Transaction Type'] = test_file['SideA.ViewData.Transaction Type'].apply(lambda x : mhreplaced(x))

In [4999]:
##############

values_transaction_type_match_A_Side = test_file['SideA.ViewData.Transaction Type'].values
values_transaction_type_match_B_Side = test_file['SideB.ViewData.Transaction Type'].values

vec_tt_match = np.vectorize(mhreplaced)

#test_file['ISIN_match'] = vec_(values_ISIN_A_Side,values_ISIN_B_Side)
#test_file['SideA.ViewData.Fund'] = test_file.apply(lambda x : fundmatch(x['SideA.ViewData.Fund']), axis=1)
test_file['SideA.ViewData.Transaction Type'] = vec_tt_match(values_transaction_type_match_A_Side)
#test_file['SideB.ViewData.Fund'] = test_file.apply(lambda x : fundmatch(x['SideB.ViewData.Fund']), axis=1)
test_file['SideB.ViewData.Transaction Type'] = vec_tt_match(values_transaction_type_match_B_Side)

In [5000]:
test_file['ViewData.Combined Transaction Type'] = test_file['SideA.ViewData.Transaction Type'].astype(str) +  test_file['SideB.ViewData.Transaction Type'].astype(str)

In [5001]:
#train_full_new1['ViewData.Combined Transaction Type'] = train_full_new1['SideA.ViewData.Transaction Type'].astype(str) + train_full_new1['SideB.ViewData.Transaction Type'].astype(str)
test_file['ViewData.Combined Fund'] = test_file['SideA.ViewData.Fund'].astype(str) + test_file['SideB.ViewData.Fund'].astype(str)

In [5002]:
def nan_fun(x):
    if x=='nan':
        return 1
    else:
        return 0
    
vec_nan_fun = np.vectorize(nan_fun)
values_ISIN_A_Side = test_file['SideA.ViewData.ISIN'].values
values_ISIN_B_Side = test_file['SideB.ViewData.ISIN'].values
test_file['SideA.ISIN_NA'] = vec_nan_fun(values_ISIN_A_Side)
test_file['SideB.ISIN_NA'] = vec_nan_fun(values_ISIN_A_Side)

#test_file['SideA.ISIN_NA'] =  test_file.apply(lambda x: 1 if x['SideA.ViewData.ISIN']=='nan' else 0, axis=1)
#test_file['SideB.ISIN_NA'] =  test_file.apply(lambda x: 1 if x['SideB.ViewData.ISIN']=='nan' else 0, axis=1)

In [5666]:
len(test_file['SideB.ViewData.CUSIP'].values)

1074857

In [5669]:
def a_keymatch(a_cusip, a_isin):
    
    pb_nan = 0
    a_common_key = 'NA' 
    if a_cusip=='nan' and a_isin =='nan':
        pb_nan =1
    elif(a_cusip!='nan' and a_isin == 'nan'):
        a_common_key = a_cusip
    elif(a_cusip =='nan' and a_isin !='nan'):
        a_common_key = a_isin
    else:
        a_common_key = a_isin
        
    return (pb_nan, a_common_key)

def b_keymatch(b_cusip, b_isin):
    accounting_nan = 0
    b_common_key = 'NA'
    if b_cusip =='nan' and b_isin =='nan':
        accounting_nan =1
    elif (b_cusip!='nan' and b_isin == 'nan'):
        b_common_key = b_cusip
    elif(b_cusip =='nan' and b_isin !='nan'):
        b_common_key = b_isin
    else:
        b_common_key = b_isin
    return (accounting_nan, b_common_key)

    
vec_a_key_match_fun = np.vectorize(a_keymatch)
vec_b_key_match_fun = np.vectorize(b_keymatch)

values_ISIN_A_Side = test_file['SideA.ViewData.ISIN'].values
values_ISIN_B_Side = test_file['SideB.ViewData.ISIN'].values

values_CUSIP_A_Side = test_file['SideA.ViewData.CUSIP'].values
values_CUSIP_B_Side = test_file['SideB.ViewData.CUSIP'].values

test_file['SideB.ViewData.key_NAN']= vec_a_key_match_fun(values_CUSIP_B_Side,values_ISIN_B_Side)[0]
test_file['SideB.ViewData.Common_key'] = vec_a_key_match_fun(values_CUSIP_B_Side,values_ISIN_B_Side)[1]
test_file['SideA.ViewData.key_NAN'] = vec_b_key_match_fun(values_CUSIP_A_Side,values_ISIN_A_Side)[0]
test_file['SideA.ViewData.Common_key'] = vec_b_key_match_fun(values_CUSIP_A_Side,values_ISIN_A_Side)[1]

In [ ]:
#test_file[['SideB.ViewData.key_NAN','SideB.ViewData.Common_key']] = test_file.apply(lambda x: b_keymatch(x['SideB.ViewData.CUSIP'], x['SideB.ViewData.ISIN']), axis=1)
#test_file[['SideA.ViewData.key_NAN','SideA.ViewData.Common_key']] = test_file.apply(lambda x: a_keymatch(x['SideA.ViewData.CUSIP'],x['SideA.ViewData.ISIN']), axis=1)

In [ ]:
def nan_equals_fun(a,b):
    if a==1 and b==1:
        return 1
    else:
        return 0
    
vec_nan_equal_fun = np.vectorize(nan_equals_fun)
values_key_NAN_B_Side = test_file['SideB.ViewData.key_NAN'].values
values_key_NAN_A_Side = test_file['SideA.ViewData.key_NAN'].values
test_file['All_key_nan'] = vec_nan_equal_fun(values_key_NAN_B_Side,values_key_NAN_A_Side )

#test_file['All_key_nan'] = test_file.apply(lambda x: 1 if x['SideB.ViewData.key_NAN']==1 and x['SideA.ViewData.key_NAN']==1 else 0, axis=1)

In [5005]:
test_file['SideB.ViewData.Common_key'] = test_file['SideB.ViewData.Common_key'].astype(str)
test_file['SideA.ViewData.Common_key'] = test_file['SideA.ViewData.Common_key'].astype(str)


def new_key_match_fun(a,b,c):
    if a==b and c==0:
        return 1
    else:
        return 0
    
vec_new_key_match_fun = np.vectorize(new_key_match_fun)
values_Common_key_B_Side = test_file['SideB.ViewData.Common_key'].values
values_Common_key_A_Side = test_file['SideA.ViewData.Common_key'].values
values_All_key_NAN = test_file['All_key_nan'].values

test_file['new_key_match']= vec_new_key_match_fun(values_Common_key_B_Side,values_Common_key_A_Side,values_All_key_NAN)

In [5006]:

#test_file['new_key_match'] = test_file.apply(lambda x: 1 if x['SideB.ViewData.Common_key']==x['SideA.ViewData.Common_key'] and x['All_key_nan']==0 else 0, axis=1)

In [5007]:
model_cols = ['SideA.ViewData.B-P Net Amount',
 'SideA.ViewData.Price',
 'SideA.ViewData.Quantity',
 'SideB.ViewData.Accounting Net Amount',
 'SideB.ViewData.Price',
 'SideB.ViewData.Quantity',
 'SideB.ViewData.Status',
 'SideB.ViewData.BreakID_B_side',
 'SideA.ViewData.Status',
 'SideA.ViewData.BreakID_A_side',
              
'SideA.ViewData._ID',
'SideB.ViewData._ID',
              
 'Trade_Date_match',
 'Settle_Date_match',
 'Amount_diff_2',
 'Trade_date_diff',
 'Settle_date_diff',
 'SideA.ISIN_NA',
 'SideB.ISIN_NA',
 'ViewData.Combined Fund',
 'ViewData.Combined Transaction Type',
 'All_key_nan',
 'new_key_match',
              
'SideB.ViewData.Side0_UniqueIds',
'SideA.ViewData.Side1_UniqueIds']
 #'label']

In [5008]:
model_cols = [
 #   'SideA.ViewData.Accounting Net Amount',
 'SideA.ViewData.B-P Net Amount',
 'SideA.ViewData.Price',
 'SideA.ViewData.Quantity',
 'SideB.ViewData.Accounting Net Amount',
# 'SideB.ViewData.B-P Net Amount',
 'SideB.ViewData.Price',
 'SideB.ViewData.Quantity',  
 'Trade_Date_match',
 'Settle_Date_match',
# 'Fund_match',
 'Amount_diff_2',
 'Trade_date_diff',
 'Settle_date_diff',
 
'SideA.ISIN_NA',
 'SideB.ISIN_NA',
    
 'ViewData.Combined Fund',
 'ViewData.Combined Transaction Type',
 'All_key_nan',
 'new_key_match',

'SideA.ViewData._ID',
'SideB.ViewData._ID',
    
'SideB.ViewData.Status',
 'SideB.ViewData.BreakID_B_side',
 'SideA.ViewData.Status',
 'SideA.ViewData.BreakID_A_side',
 'SideB.ViewData.Side0_UniqueIds',
'SideA.ViewData.Side1_UniqueIds']

In [4933]:
#test_file.to_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/X_test_files_after_loop/meo_testing_HST_RecData_170_06-18-2020_test_file.csv")

In [930]:
#test_file['SideA.ViewData.BreakID_A_side'].value_counts()

In [4299]:
test_file = pd.read_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/X_Test/x_test_125_2020-06-8.csv")

In [4300]:
test_file = test_file.drop('Unnamed: 0',1)

## Test file served into the model

In [5009]:
X_test = test_file[model_cols]

In [5010]:
X_test = X_test.reset_index()
X_test = X_test.drop('index',1)

In [5011]:
X_test = X_test.fillna(0)

In [5012]:
X_test.shape

(1074857, 25)

In [5013]:
X_test = X_test.drop_duplicates()
X_test = X_test.reset_index()
X_test = X_test.drop('index',1)

In [5014]:
X_test.shape

(1072923, 25)

## Model Pickle file import

In [5015]:
import pickle

In [5016]:
#filename = 'Oak_W125_model_with_umb.sav'
#filename = '125_with_umb_without_des_and_many_to_many.sav'
#filename = '125_with_umb_and_price_without_des_and_many_to_many_tdsd2.sav'
filename = 'Weiss_new_model_V1.sav'
clf = pickle.load(open(filename, 'rb'))

In [5017]:
X_test['Amount_diff_2'].max()

81420738.01

In [5018]:
X_test[['ViewData.Combined Transaction Type','ViewData.Combined Fund','All_key_nan', 'new_key_match','Trade_Date_match','Settle_Date_match', 'SideA.ISIN_NA','SideB.ISIN_NA']].dtypes

ViewData.Combined Transaction Type    object
ViewData.Combined Fund                object
All_key_nan                            int64
new_key_match                          int64
Trade_Date_match                       int32
Settle_Date_match                      int32
SideA.ISIN_NA                          int32
SideB.ISIN_NA                          int32
dtype: object

## Predictions

In [5019]:
# Actual class predictions
rf_predictions = clf.predict(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))
# Probabilities for each class
rf_probs = clf.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 1]

In [5020]:
probability_class_0 = clf1.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side','SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 0]
probability_class_1 = clf1.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 1]

probability_class_2 = clf1.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side','SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 2]
probability_class_3 = clf1.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 3]

#probability_class_4 = clf1.predict_proba(X_test.drop(['SideB.ViewData.Status','SideB.ViewData.BreakID_B_side', 'SideA.ViewData.Status','SideA.ViewData.BreakID_A_side','SideA.ViewData._ID','SideB.ViewData._ID','SideB.ViewData.Side0_UniqueIds','SideA.ViewData.Side1_UniqueIds'],1))[:, 4]

In [5021]:
X_test['Predicted_action'] = rf_predictions
#X_test['Predicted_action_probabilty'] = rf_probs
X_test['probability_No_pair'] = probability_class_0
#X_test['probability_Partial_match'] = probability_class_1
#X_test['probability_UMB'] = probability_class_1
X_test['probability_UMB'] = probability_class_1
X_test['probability_UMR'] = probability_class_2
X_test['probability_UMT'] = probability_class_3

In [5022]:
X_test['Predicted_action'].value_counts()

No-Pair           1071508
UMT_One_to_One       1051
UMR_One_to_One        351
UMB_One_to_One         13
Name: Predicted_action, dtype: int64

## Prediction Table

In [5023]:
X_test.loc[(X_test['Predicted_action']=='UMR_One_to_One') & ((X_test['Amount_diff_2']!=0) | (X_test['Amount_diff_2']!=0)),'Predicted_action'] = 'Unrecognized'

In [5024]:
pd.set_option('max_columns', 100)

In [5025]:
X_test[X_test['Predicted_action']=='UMB_One_to_One']

,SideA.ViewData.B-P Net Amount,SideA.ViewData.Price,SideA.ViewData.Quantity,SideB.ViewData.Accounting Net Amount,SideB.ViewData.Price,SideB.ViewData.Quantity,Trade_Date_match,Settle_Date_match,Amount_diff_2,Trade_date_diff,Settle_date_diff,SideA.ISIN_NA,SideB.ISIN_NA,ViewData.Combined Fund,ViewData.Combined Transaction Type,All_key_nan,new_key_match,SideA.ViewData._ID,SideB.ViewData._ID,SideB.ViewData.Status,SideB.ViewData.BreakID_B_side,SideA.ViewData.Status,SideA.ViewData.BreakID_A_side,SideB.ViewData.Side0_UniqueIds,SideA.ViewData.Side1_UniqueIds,Predicted_action,probability_No_pair,probability_UMB,probability_UMR,probability_UMT
36940,37703.42,85.2667,-4994.0,32462.49,212.4919,-153.0,1,1,-5240.93,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bad,5ee0725a155458281413ec04,SDB,1290790565,SDB,1326731492,469_125850828_Advent Geneva,1021_125845307_Goldman Sachs,UMB_One_to_One,0.968838,0.010647,0.011084,0.009431
37548,20378.07,866.4625,-269.0,-13806.65,109.7841,-2411.0,1,1,-34184.72,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141b21,5ee072861554582814141c62,OB,1326735525,SPM,1326731534,548_125891903_Advent Geneva,842_125849133_Goldman Sachs,UMB_One_to_One,0.958468,0.012524,0.015830,0.013178
37574,20378.07,866.4625,-269.0,4.41,80.5771,-1195.0,1,1,-20373.66,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141b21,5ee072861554582814141c27,OB,1326735498,SPM,1326731534,550_125891903_Advent Geneva,842_125849133_Goldman Sachs,UMB_One_to_One,0.959148,0.012935,0.015232,0.012684
37808,4.42,80.4563,-1195.0,-13806.65,109.7841,-2411.0,1,1,-13811.07,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bac,5ee072861554582814141c62,OB,1326735525,SDB,1326731549,548_125891903_Advent Geneva,844_125849133_Goldman Sachs,UMB_One_to_One,0.972107,0.008626,0.010539,0.008728
37832,4.42,80.4563,-1195.0,20378.07,867.7641,-269.0,1,1,20373.65,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bac,5ee072861554582814141b33,SPM,1326735491,SDB,1326731549,546_125891903_Advent Geneva,844_125849133_Goldman Sachs,UMB_One_to_One,0.975279,0.007222,0.009646,0.007853
38092,-13806.83,109.6194,-2411.0,20378.07,867.7641,-269.0,1,1,34184.90,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bae,5ee072861554582814141b33,SPM,1326735491,SDB,1326731551,546_125891903_Advent Geneva,849_125849133_Goldman Sachs,UMB_One_to_One,0.958142,0.012074,0.016410,0.013374
38325,-9701.93,75.8345,-3959.0,-1930.07,114.4032,-1732.0,1,1,7771.86,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb0,5ee072861554582814141c4a,OB,1326735519,SDB,1326731568,756_125891903_Advent Geneva,1321_125864080_Goldman Sachs,UMB_One_to_One,0.971247,0.008512,0.011162,0.009078
38331,-9701.93,75.8345,-3959.0,-18283.01,75.9484,-3959.0,1,1,-8581.08,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb0,5ee072861554582814141c4c,OB,1326735530,SDB,1326731568,758_125891903_Advent Geneva,1321_125864080_Goldman Sachs,UMB_One_to_One,0.971410,0.009114,0.010557,0.008918
38591,-1930.14,114.2316,-1732.0,-18283.01,75.9484,-3959.0,1,1,-16352.87,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb1,5ee072861554582814141c4c,OB,1326735530,SDB,1326731608,758_125891903_Advent Geneva,1323_125864080_Goldman Sachs,UMB_One_to_One,0.957494,0.012924,0.016200,0.013382
38849,-29125.51,16.6039,11955.0,-10735.53,448.6224,988.0,1,1,18389.98,0.0,0.0,1,1,06271287LF,buybuy,0,0,5ee072861554582814141bb4,5ee072861554582814141c4b,OB,1326735526,SDB,1326731687,907_125891903_Advent Geneva,1171_125877243_Goldman Sachs,UMB_One_to_One,0.971638,0.008105,0.011725,0.008532
39893,-51952.69,17.6657,13675.0,-20794.01,468.9015,667.0,1,1,31158.68,0.0,0.0,1,1,06271287LF,buybuy,0,0,5ee072861554582814141bbc,5ee072861554582814141c59,OB,1326735536,SDB,1326731803,923_125891903_Advent Geneva,1231_125878995_Goldman Sachs,UMB_One_to_One,0.971638,0.008105,0.011725,0.008532
40666,10078.12,84.8807,-6279.0,13643.53,129.7526,-960.0,1,1,3565.41,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bc1,5ee072861554582814141c57,OB,1326735522,SDB,1326731845,999_125891903_Advent Geneva,949_125886443_Goldman Sachs,UMB_One_to_One,0.972914,0.007737,0.010585,0.008764
40953,13643.52,129.5580,-960.0,10078.08,85.0082,-6279.0,1,1,-3565.44,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bc2,5ee072861554582814141c20,OB,1326735495,SDB,1326731871,997_125891903_Advent Geneva,952_125886443_Goldman Sachs,UMB_One_to_One,0.956508,0.014499,0.015875,0.013119

In [5026]:
###### Probability filter for UMT and UMB ################

#X_test.loc[(X_test['Predicted_action']=='UMT_One_to_One') & (X_test['probability_UMT']<0.90) & (X_test['probability_No_pair']>0.05),'Predicted_action'] = 'No-Pair' 

#X_test.loc[(X_test['Predicted_action']=='UMB_One_to_One') & (X_test['probability_UMB']<0.75) & (X_test['probability_No_pair']>0.2),'Predicted_action'] = 'No-Pair' 

#X_test.loc[(X_test['Predicted_action']=='UMR_One_to_One') & (X_test['probability_UMR']<0.90) & (X_test['probability_No_pair']>0.05),'Predicted_actionX_test.loc[(X_test['Predicted_action']=='No-Pair') & (X_test['probability_No_pair']<0.9) & (X_test['probability_UMB']>0.05),'Predicted_action'] = 'UMB_One_to_One' 


#X_test.loc[(X_test['Predicted_action']=='No-Pair') & (X_test['probability_No_pair']<0.95) & (X_test['probability_UMB']>0.05),'Predicted_action'] = 'UMB_One_to_One' 

#X_test.loc[(X_test['Predicted_action']=='UMR_One_to_One') & (X_test['Settle_date_diff']>4),'Predicted_action'] = 'No-Pair' 
#X_test.loc[(X_test['Predicted_action']=='UMR_One_to_One') & (X_test['Settle_date_diff']<-4),'Predicted_action'] = 'No-Pair'

In [5027]:
#X_test.loc[(X_test['SideB.ViewData.Status']=='SDB') & (X_test['SideA.ViewData.Status']=='OB') & (X_test['Predicted_action']=='No-Pair'),'Predicted_action'] = 'SDB/Open Break'

In [5028]:
prediction_table =  X_test.groupby('SideB.ViewData.BreakID_B_side')['Predicted_action'].unique().reset_index()

In [5029]:
#prob1 = X_test.groupby('SideB.ViewData.BreakID_B_side')['probability_No_pair'].mean().reset_index()

In [5030]:
prediction_table['len'] = prediction_table['Predicted_action'].str.len()

In [5031]:
prediction_table['No_Pair_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'No-Pair' in x else 0)

In [5032]:
prediction_table['UMB_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'UMB_One_to_One' in x else 0)
prediction_table['UMT_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'UMT_One_to_One' in x else 0)
prediction_table['UMR_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'UMR_One_to_One' in x else 0)

In [5033]:
prediction_table

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag
0,952496851,[No-Pair],1,1,0,0,0
1,959509436,[No-Pair],1,1,0,0,0
2,967115733,"[No-Pair, UMT_One_to_One]",2,1,0,1,0
3,967115815,[No-Pair],1,1,0,0,0
4,967115839,[No-Pair],1,1,0,0,0
...,...,...,...,...,...,...,...
3642,1329848340,"[No-Pair, UMT_One_to_One]",2,1,0,1,0
3643,1329848341,[No-Pair],1,1,0,0,0
3644,1329848342,[No-Pair],1,1,0,0,0
3645,1329848343,"[No-Pair, UMT_One_to_One]",2,1,0,1,0
3646,1329848347,[No-Pair],1,1,0,0,0

In [5034]:
X_test[X_test['Predicted_action']=='UMB_One_to_One']

,SideA.ViewData.B-P Net Amount,SideA.ViewData.Price,SideA.ViewData.Quantity,SideB.ViewData.Accounting Net Amount,SideB.ViewData.Price,SideB.ViewData.Quantity,Trade_Date_match,Settle_Date_match,Amount_diff_2,Trade_date_diff,Settle_date_diff,SideA.ISIN_NA,SideB.ISIN_NA,ViewData.Combined Fund,ViewData.Combined Transaction Type,All_key_nan,new_key_match,SideA.ViewData._ID,SideB.ViewData._ID,SideB.ViewData.Status,SideB.ViewData.BreakID_B_side,SideA.ViewData.Status,SideA.ViewData.BreakID_A_side,SideB.ViewData.Side0_UniqueIds,SideA.ViewData.Side1_UniqueIds,Predicted_action,probability_No_pair,probability_UMB,probability_UMR,probability_UMT
36940,37703.42,85.2667,-4994.0,32462.49,212.4919,-153.0,1,1,-5240.93,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bad,5ee0725a155458281413ec04,SDB,1290790565,SDB,1326731492,469_125850828_Advent Geneva,1021_125845307_Goldman Sachs,UMB_One_to_One,0.968838,0.010647,0.011084,0.009431
37548,20378.07,866.4625,-269.0,-13806.65,109.7841,-2411.0,1,1,-34184.72,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141b21,5ee072861554582814141c62,OB,1326735525,SPM,1326731534,548_125891903_Advent Geneva,842_125849133_Goldman Sachs,UMB_One_to_One,0.958468,0.012524,0.015830,0.013178
37574,20378.07,866.4625,-269.0,4.41,80.5771,-1195.0,1,1,-20373.66,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141b21,5ee072861554582814141c27,OB,1326735498,SPM,1326731534,550_125891903_Advent Geneva,842_125849133_Goldman Sachs,UMB_One_to_One,0.959148,0.012935,0.015232,0.012684
37808,4.42,80.4563,-1195.0,-13806.65,109.7841,-2411.0,1,1,-13811.07,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bac,5ee072861554582814141c62,OB,1326735525,SDB,1326731549,548_125891903_Advent Geneva,844_125849133_Goldman Sachs,UMB_One_to_One,0.972107,0.008626,0.010539,0.008728
37832,4.42,80.4563,-1195.0,20378.07,867.7641,-269.0,1,1,20373.65,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bac,5ee072861554582814141b33,SPM,1326735491,SDB,1326731549,546_125891903_Advent Geneva,844_125849133_Goldman Sachs,UMB_One_to_One,0.975279,0.007222,0.009646,0.007853
38092,-13806.83,109.6194,-2411.0,20378.07,867.7641,-269.0,1,1,34184.90,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bae,5ee072861554582814141b33,SPM,1326735491,SDB,1326731551,546_125891903_Advent Geneva,849_125849133_Goldman Sachs,UMB_One_to_One,0.958142,0.012074,0.016410,0.013374
38325,-9701.93,75.8345,-3959.0,-1930.07,114.4032,-1732.0,1,1,7771.86,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb0,5ee072861554582814141c4a,OB,1326735519,SDB,1326731568,756_125891903_Advent Geneva,1321_125864080_Goldman Sachs,UMB_One_to_One,0.971247,0.008512,0.011162,0.009078
38331,-9701.93,75.8345,-3959.0,-18283.01,75.9484,-3959.0,1,1,-8581.08,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb0,5ee072861554582814141c4c,OB,1326735530,SDB,1326731568,758_125891903_Advent Geneva,1321_125864080_Goldman Sachs,UMB_One_to_One,0.971410,0.009114,0.010557,0.008918
38591,-1930.14,114.2316,-1732.0,-18283.01,75.9484,-3959.0,1,1,-16352.87,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bb1,5ee072861554582814141c4c,OB,1326735530,SDB,1326731608,758_125891903_Advent Geneva,1323_125864080_Goldman Sachs,UMB_One_to_One,0.957494,0.012924,0.016200,0.013382
38849,-29125.51,16.6039,11955.0,-10735.53,448.6224,988.0,1,1,18389.98,0.0,0.0,1,1,06271287LF,buybuy,0,0,5ee072861554582814141bb4,5ee072861554582814141c4b,OB,1326735526,SDB,1326731687,907_125891903_Advent Geneva,1171_125877243_Goldman Sachs,UMB_One_to_One,0.971638,0.008105,0.011725,0.008532
39893,-51952.69,17.6657,13675.0,-20794.01,468.9015,667.0,1,1,31158.68,0.0,0.0,1,1,06271287LF,buybuy,0,0,5ee072861554582814141bbc,5ee072861554582814141c59,OB,1326735536,SDB,1326731803,923_125891903_Advent Geneva,1231_125878995_Goldman Sachs,UMB_One_to_One,0.971638,0.008105,0.011725,0.008532
40666,10078.12,84.8807,-6279.0,13643.53,129.7526,-960.0,1,1,3565.41,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bc1,5ee072861554582814141c57,OB,1326735522,SDB,1326731845,999_125891903_Advent Geneva,949_125886443_Goldman Sachs,UMB_One_to_One,0.972914,0.007737,0.010585,0.008764
40953,13643.52,129.5580,-960.0,10078.08,85.0082,-6279.0,1,1,-3565.44,0.0,0.0,1,1,06271287LF,sellsell,0,0,5ee072861554582814141bc2,5ee072861554582814141c20,OB,1326735495,SDB,1326731871,997_125891903_Advent Geneva,952_125886443_Goldman Sachs,UMB_One_to_One,0.956508,0.014499,0.015875,0.013119

In [5035]:
umr_array = X_test[X_test['Predicted_action']=='UMR_One_to_One'].groupby(['SideB.ViewData.BreakID_B_side'])['SideA.ViewData.BreakID_A_side'].unique().reset_index()
umt_array = X_test[X_test['Predicted_action']=='UMT_One_to_One'].groupby(['SideB.ViewData.BreakID_B_side'])['SideA.ViewData.BreakID_A_side'].unique().reset_index()
umb_array = X_test[X_test['Predicted_action']=='UMB_One_to_One'].groupby(['SideB.ViewData.BreakID_B_side'])['SideA.ViewData.BreakID_A_side'].unique().reset_index()

In [5036]:
umr_array.columns = ['SideB.ViewData.BreakID_B_side', 'Predicted_UMR_array']
umt_array.columns = ['SideB.ViewData.BreakID_B_side', 'Predicted_UMT_array']
umb_array.columns = ['SideB.ViewData.BreakID_B_side', 'Predicted_UMB_array']

In [5037]:
prediction_table = pd.merge(prediction_table,umr_array, on='SideB.ViewData.BreakID_B_side', how='left' )
prediction_table = pd.merge(prediction_table,umt_array, on='SideB.ViewData.BreakID_B_side', how='left' )
prediction_table = pd.merge(prediction_table,umb_array, on='SideB.ViewData.BreakID_B_side', how='left' )

In [5038]:
#prediction_table
#X_test[X_test['SideB.ViewData.Side0_UniqueIds']=='2495_125897734_Advent Geneva']

prediction_table[prediction_table['SideB.ViewData.BreakID_B_side'] == 1334352050]

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array]
Index: []

In [5039]:
prediction_table['Final_prediction'] = prediction_table.apply(lambda x: 'UMR_One_to_One' if x['UMR_flag']==1 else('UMT_One_to_One' if x['len']==1 and x['UMT_flag']==1 else('UMB_One_to_UMB' if x['len']==1 and x['UMB_flag']==1 else('No-Pair' if x['len']==1 else 'Undecided'))), axis=1)

In [5040]:
prediction_table['Final_prediction'].value_counts()

No-Pair           2871
Undecided          458
UMR_One_to_One     311
UMT_One_to_One       7
Name: Final_prediction, dtype: int64

In [5041]:
prediction_table['Final_prediction'].value_counts()

No-Pair           2871
Undecided          458
UMR_One_to_One     311
UMT_One_to_One       7
Name: Final_prediction, dtype: int64

In [5042]:
prediction_table['UMT_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'UMT_One_to_One' in x else 0)
prediction_table['UMB_flag'] = prediction_table['Predicted_action'].apply(lambda x: 1 if 'UMB_One_to_One' in x else 0)

In [5043]:
prediction_table.loc[(prediction_table['UMB_flag']==1) & (prediction_table['len']==2),'Final_prediction']='UMB_One_to_One'
prediction_table.loc[(prediction_table['UMT_flag']==1) & (prediction_table['len']==2),'Final_prediction']='UMT_One_to_One'

In [5044]:
prediction_table.loc[(prediction_table['Final_prediction']=='Undecided') & (prediction_table['len']==2),'Final_prediction']='No-Pair/Unrecognized'

In [5045]:
prediction_table.loc[(prediction_table['Final_prediction']=='Undecided') & (prediction_table['UMT_flag']==1),'Final_prediction']='UMT_One_to_One'

In [5046]:
prediction_table.loc[(prediction_table['Final_prediction']=='Undecided') & (prediction_table['UMB_flag']==1),'Final_prediction']='UMB_One_to_One'

In [5047]:
prediction_table['Final_prediction'].value_counts()

No-Pair           2871
UMT_One_to_One     464
UMR_One_to_One     311
UMB_One_to_One       1
Name: Final_prediction, dtype: int64

In [5048]:
prediction_table[prediction_table['SideB.ViewData.BreakID_B_side'] == 1334352050]

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction]
Index: []

In [5049]:
#X_test[(X_test['Predicted_action']=='UMR_One_to_One') & (X_test['SideB.ViewData.BreakID_B_side']==1346769635)]

In [5050]:
prediction_table.loc[prediction_table['Final_prediction']=='UMR_One_to_One', 'Final_predicted_break'] = prediction_table.loc[prediction_table['Final_prediction']=='UMR_One_to_One', 'Predicted_UMR_array']

In [5051]:
prediction_table.loc[prediction_table['Final_prediction']=='UMT_One_to_One', 'Final_predicted_break'] = prediction_table.loc[prediction_table['Final_prediction']=='UMT_One_to_One', 'Predicted_UMT_array']
prediction_table.loc[prediction_table['Final_prediction']=='UMB_One_to_One', 'Final_predicted_break'] = prediction_table.loc[prediction_table['Final_prediction']=='UMB_One_to_One', 'Predicted_UMB_array']
#prediction_table.loc[prediction_table['Final_prediction']=='No-Pair', 'Final_predicted_break'] = prediction_table.loc[prediction_table['Final_prediction']=='No-Pair', '']

In [5052]:
prediction_table['predicted_break_len'] = prediction_table['Final_predicted_break'].str.len()

In [5053]:
prediction_table[prediction_table['SideB.ViewData.BreakID_B_side'] == 1334352050]

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len]
Index: []

In [5054]:
#prediction_table[(prediction_table['predicted_break_len']>1) & (prediction_table['Final_prediction']=='UMT_One_to_One')]

In [5055]:
#prediction_table[['SideB.ViewData.BreakID_B_side', 'Final_prediction', 'Final_predicted_break']]

In [5056]:
X_test['prob_key'] = X_test['SideB.ViewData.BreakID_B_side'].astype(str) + X_test['Predicted_action']
prediction_table['prob_key'] = prediction_table['SideB.ViewData.BreakID_B_side'].astype(str) + prediction_table['Final_prediction']

In [5057]:
user_prob = X_test.groupby('prob_key')[['probability_UMR','probability_UMT','probability_UMB']].max().reset_index()
open_prob = X_test.groupby('prob_key')['probability_No_pair'].mean().reset_index()

In [5058]:
#prediction_table = prediction_table.drop(,1)

prediction_table = pd.merge(prediction_table,user_prob, on='prob_key', how='left')
prediction_table = pd.merge(prediction_table,open_prob, on='prob_key', how='left')

In [5059]:
prediction_table = prediction_table.drop('prob_key',1)

In [5060]:
prediction_table[prediction_table['SideB.ViewData.BreakID_B_side'] == 1334352050]

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair]
Index: []

In [5061]:
prediction_table

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair
0,952496851,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.105910,0.176388,0.129583,0.954913
1,959509436,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.075652,0.134378,0.135453,0.951449
2,967115733,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,"[1327140659, 1327141078]",NaN,UMT_One_to_One,"[1327140659, 1327141078]",2.0,0.208124,0.163815,0.152302,0.487354
3,967115815,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.160135,0.770441
4,967115839,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.143237,0.931756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3642,1329848340,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329848346],NaN,UMT_One_to_One,[1329848346],1.0,0.170127,0.341575,0.159862,0.328436
3643,1329848341,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.009869,0.007887,0.007430,0.986733
3644,1329848342,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.010880,0.008551,0.009224,0.979510
3645,1329848343,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329847179],NaN,UMT_One_to_One,[1329847179],1.0,0.122482,0.396144,0.050465,0.430908
3646,1329848347,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.005779,0.004466,0.003528,0.989149

In [5062]:
prediction_table = pd.merge(prediction_table, X_test[['SideB.ViewData.BreakID_B_side','SideA.ViewData._ID','SideB.ViewData._ID']].drop_duplicates(['SideB.ViewData.BreakID_B_side','SideB.ViewData._ID']), on ='SideB.ViewData.BreakID_B_side', how='left')

In [5063]:
prediction_table[prediction_table['SideB.ViewData.BreakID_B_side'] ==1334352050]

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID]
Index: []

In [5064]:
prediction_table.dtypes

SideB.ViewData.BreakID_B_side      int64
Predicted_action                  object
len                                int64
No_Pair_flag                       int64
UMB_flag                           int64
UMT_flag                           int64
UMR_flag                           int64
Predicted_UMR_array               object
Predicted_UMT_array               object
Predicted_UMB_array               object
Final_prediction                  object
Final_predicted_break             object
predicted_break_len              float64
probability_UMR                  float64
probability_UMT                  float64
probability_UMB                  float64
probability_No_pair              float64
SideA.ViewData._ID                object
SideB.ViewData._ID                object
dtype: object

## Merging PB side Break ID's

In [5065]:
#pb_break_ids = prediction_table[~prediction_table['Final_predicted_break'].isnull()][['Final_prediction','Final_predicted_break']]

In [4358]:
#pb_break_ids = pb_break_ids.reset_index()
#pb_break_ids = pb_break_ids.drop('index',1)

In [1706]:
#pb_break_ids['Final_predicted_break'] = pb_break_ids['Final_predicted_break'].apply(lambda x: str(x).replace("[",''))
#pb_break_ids['Final_predicted_break'] = pb_break_ids['Final_predicted_break'].apply(lambda x: str(x).replace("]",''))

In [2444]:
#pb_break_ids['Final_predicted_break'].unique()

In [1708]:
#id_list = []
#id_list2 = []

#for i in pb_break_ids['Final_predicted_break'].unique():
#    id_list.append(i.split(' '))
#for j in np.concatenate(id_list,axis=0):
#    if j!='':
#        id_list2.append(j.replace("\n",''))

In [1709]:
#new_ob_ids =[]
#
#for i in X_test['SideA.ViewData.BreakID_A_side'].astype(str).unique():
#    if i not in np.array(id_list2,dtype="O"):
#        new_ob_ids.append(i)

In [1710]:
#prediction_table2 = pd.DataFrame(np.array(new_ob_ids))

In [1711]:
#prediction_table2.columns = ['SideB.ViewData.BreakID_B_side']

In [1712]:
#prediction_table2['Final_prediction'] = 'No-Pair'

In [1713]:
#prediction_table2['Side'] = 'P-B Side'

In [1714]:
#prediction_table['Side'] = 'Accounting Side'

In [2074]:
#prediction_table3 = prediction_table

In [2442]:
#prediction_table3 = pd.concat([prediction_table, prediction_table2], axis=0)

In [1716]:
#prediction_table3 = prediction_table3.reset_index()
#prediction_table3 = prediction_table3.drop('index',1)

In [1717]:
#prediction_table3 = prediction_table3[prediction_table.columns]

In [2443]:
#prediction_table3[['SideB.ViewData.BreakID_B_side', 'Final_prediction', 'Final_predicted_break','Side']]

In [1719]:
#ids_for_comment = prediction_table3[['SideB.ViewData.BreakID_B_side', 'Final_prediction', 'Final_predicted_break','Side']]

In [2445]:
#ids_for_comment

In [1721]:
#ids_for_comment.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/Input for comment prediction/prediction_table_testing_HST_RecData_125_1159652110_06-19-2020.csv')

## Merging with User Action Data

In [5474]:
prediction_table3 = prediction_table

In [5475]:
aua = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/AUA/AUACollections.AUA_HST_RecData_125_2020-06-8.csv')

In [5476]:
#test_file.to_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/OakTree/JuneData/X_Test/x_test_2020-06-29.csv")

In [5477]:
aua.shape

(2477, 230)

In [5478]:
aua = aua[~((aua['LastPerformedAction']==0) & (aua['ViewData.Status']=='SDB'))]
aua = aua.reset_index()
aua = aua.drop('index',1)

In [5479]:
aua['ViewData.Status'].value_counts()

OB     1064
UCB     521
UDB     290
UMR     219
UMT      82
SDB      28
UCC      20
UMB      14
SMB      10
Name: ViewData.Status, dtype: int64

In [5480]:
aua = aua[aua['ViewData.Status'].isin(['UMR','UMB','UMT','OB','SDB','UCB'])]
aua = aua.reset_index()
aua = aua.drop('index',1)

In [5481]:
aua['ViewData.Status'].value_counts()

OB     1064
UCB     521
UMR     219
UMT      82
SDB      28
UMB      14
Name: ViewData.Status, dtype: int64

In [5482]:
prediction_table3

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID
0,952496851,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.105910,0.176388,0.129583,0.954913,5ee072861554582814141bd6,5ee072861554582814140ed1
1,959509436,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.075652,0.134378,0.135453,0.951449,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9689
2,967115733,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,"[1327140659, 1327141078]",NaN,UMT_One_to_One,"[1327140659, 1327141078]",2.0,0.208124,0.163815,0.152302,0.487354,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9651
3,967115815,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.160135,0.770441,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9679
4,967115839,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.143237,0.931756,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3642,1329848340,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329848346],NaN,UMT_One_to_One,[1329848346],1.0,0.170127,0.341575,0.159862,0.328436,5ee1f34a1554582814566bca,5ee1f34a1554582814566f48
3643,1329848341,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.009869,0.007887,0.007430,0.986733,5ee1f34a1554582814566bca,5ee1f34a1554582814566f46
3644,1329848342,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.010880,0.008551,0.009224,0.979510,5ee1f34a1554582814566f87,5ee1f34a1554582814566f4a
3645,1329848343,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329847179],NaN,UMT_One_to_One,[1329847179],1.0,0.122482,0.396144,0.050465,0.430908,5ee1f34a1554582814566bca,5ee1f34a1554582814566f4c
3646,1329848347,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.005779,0.004466,0.003528,0.989149,5ee1f34a1554582814566bcb,5ee1f34a1554582814566f55

In [5483]:
aua_id_match = aua[['MetaData.0._ParentID','ViewData.Status','ViewData.Age','ViewData.BreakID','ViewData._ID','ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds']]

aua_id_match.columns = ['SideB.ViewData._ID','Actual_Status','ViewData.Age','ViewData.BreakID','AUA_ViewData._ID','ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds']

aua_id_match = aua_id_match.drop_duplicates()
aua_id_match = aua_id_match.reset_index()
aua_id_match = aua_id_match.drop('index',1)

########################################################################################################
aua_open_status = aua[['ViewData.BreakID','ViewData.Status']]

aua_open_status.columns = ['SideB.ViewData.BreakID_B_side','Actual_Status_Open']
aua_open_status = aua_open_status.drop_duplicates()
aua_open_status = aua_open_status.reset_index()
aua_open_status = aua_open_status.drop('index',1)

In [5484]:
aua_id_match

,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds
0,NaN,OB,0,1330102494,CombinedID:5ee20f879bbee7249c24fa09-5ee20f879b...,NaN,"304_125889670_State Street,654_125889670_State..."
1,5ee0d8c015545825a4c963d1,OB,0,1330102492,CombinedID:5ee20f879bbee7249c24f9eb-5ee20f879b...,"846_125880291_Advent Geneva,757_125891404_Adve...",NaN
2,NaN,UMR,0,1330102496,5ee20f879bbee7249c24fa4e,"846_125880291_Advent Geneva,757_125891404_Adve...","304_125889670_State Street,654_125889670_State..."
3,NaN,UCB,0,1328331329,5ee0deaf9bbee72a2895012b,NaN,34_125889670_State Street
4,NaN,UCB,0,1328247629,5ee0deaf9bbee72a2895012a,NaN,264_125893206_State Street
...,...,...,...,...,...,...,...
1759,5ee0689515545825a4b96654,OB,1,1326535069,5ee08c099bbee82088a11cc0,1270_125891836_Advent Geneva,NaN
1760,NaN,OB,5,1326535083,5ee08c099bbee82088a11cbf,NaN,1651_125891836_CITI
1761,NaN,OB,5,1326533598,5ee08c099bbee82088a11cbe,NaN,1376_125891836_CITI
1762,NaN,OB,2,1326533601,5ee08c099bbee82088a11cbd,NaN,1379_125891836_CITI
1763,5ee0689515545825a4b961e0,OB,1,1326533579,5ee08c099bbee82088a11cbc,1095_125891836_Advent Geneva,NaN

In [5485]:
aua_open_status['SideB.ViewData.BreakID_B_side'] = aua_open_status['SideB.ViewData.BreakID_B_side'].astype(int).astype(str)
prediction_table3['SideB.ViewData.BreakID_B_side'] = prediction_table3['SideB.ViewData.BreakID_B_side'].astype(int).astype(str)

In [5486]:
aua_id_match.shape

(1764, 7)

In [5487]:
prediction_table3['SideB.ViewData._ID'] = prediction_table3['SideB.ViewData._ID'].fillna('Not_generated')
prediction_table3['SideA.ViewData._ID'] = prediction_table3['SideA.ViewData._ID'].fillna('Not_generated')

In [5488]:
prediction_table3[prediction_table3['SideB.ViewData.BreakID_B_side'] == '1334352050']

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID]
Index: []

In [5489]:
#aua_id_match['len_side0'] = aua_id_match.apply(lambda x: len(x['Actual_Status'].split(',')), axis=1)
#aua_id_match['len_side1'] = aua_id_match.apply(lambda x: len(x['Actual_Status'].split(',')), axis=1)

In [5490]:
#aua_one_side = aua_id_match.groupby(['ViewData.Side1_UniqueIds'])['Actual_Status'].unique().reset_index()
#aua_zero_side = aua_id_match.groupby(['ViewData.Side0_UniqueIds'])['Actual_Status'].unique().reset_index()

In [5491]:
aua_id_match['combined_flag'] = aua_id_match.apply(lambda x: 1 if 'Combined' in x['AUA_ViewData._ID'] else 0,axis=1)

In [5492]:
#aua_id_match[''.sort_values(['ViewData.Side0_UniqueIds'])

In [5493]:
aua_id_match1  = aua_id_match[aua_id_match['combined_flag']!=1]
aua_id_match1 = aua_id_match1.reset_index()
aua_id_match1 = aua_id_match1.drop('index',1)

In [5494]:
side1_repeat = aua_id_match1['ViewData.Side1_UniqueIds'].value_counts().reset_index()
side0_repeat = aua_id_match1['ViewData.Side0_UniqueIds'].value_counts().reset_index()

In [5495]:
side1_repeat

                             index  ViewData.Side1_UniqueIds
0               396_125891836_CITI                         2
1              1541_125891836_CITI                         2
2              2105_125891836_CITI                         2
3               389_125891836_CITI                         2
4              2110_125891836_CITI                         2
..                             ...                       ...
973  2444_125892163_Morgan Stanley                         1
974   150_125892163_Morgan Stanley                         1
975   1044_125847369_Goldman Sachs                         1
976  1563_125890550_Morgan Stanley                         1
977  2131_125892163_Morgan Stanley                         1

[978 rows x 2 columns]

In [5496]:
side1_repeat[side1_repeat['ViewData.Side1_UniqueIds']>1]

                          index  ViewData.Side1_UniqueIds
0            396_125891836_CITI                         2
1           1541_125891836_CITI                         2
2           2105_125891836_CITI                         2
3            389_125891836_CITI                         2
4           2110_125891836_CITI                         2
5           2427_125891836_CITI                         2
6           2421_125891836_CITI                         2
7           1657_125891836_CITI                         2
8           1376_125891836_CITI                         2
9   943_125865402_Goldman Sachs                         2
10          1379_125891836_CITI                         2
11    9_125860170_Goldman Sachs                         2
12          2423_125891836_CITI                         2
13          2109_125891836_CITI                         2
14    6_125858636_Goldman Sachs                         2
15          1651_125891836_CITI                         2
16           395_125891836_CITI                         2
17           829_125891836_CITI                         2
18           391_125891836_CITI                         2

In [5497]:
aua_id_match1['1_repeat_flag'] = aua_id_match1.apply(lambda x: 1 if x['ViewData.Side1_UniqueIds'] in side1_repeat[side1_repeat['ViewData.Side1_UniqueIds']>1]['index'].values else 0, axis=1)
aua_id_match1['0_repeat_flag'] = aua_id_match1.apply(lambda x: 1 if x['ViewData.Side0_UniqueIds'] in side0_repeat[side0_repeat['ViewData.Side0_UniqueIds']>1]['index'].values else 0, axis=1)

In [5498]:
aua_id_match2 = aua_id_match1[~((aua_id_match1['1_repeat_flag']==1) & (aua_id_match1['Actual_Status']=='OB'))]
aua_id_match2 = aua_id_match2.reset_index()
aua_id_match2 = aua_id_match2.drop('index',1)

In [5499]:
aua_id_match3 = aua_id_match2[~((aua_id_match2['0_repeat_flag']==1) & (aua_id_match2['Actual_Status']=='OB'))]
aua_id_match3 = aua_id_match3.reset_index()
aua_id_match3 = aua_id_match3.drop('index',1)

In [5500]:

#aua_zero_side['len_side0'].value_counts()
#aua_open_status['SideB.ViewData.BreakID_B_side'].nunique()

In [5501]:
#aua_sub99[aua_sub99['ViewData.Side0_UniqueIds'] == '789_125897734_Advent Geneva']

In [5502]:
aua_id_match3[aua_id_match3['ViewData.Side0_UniqueIds'] == '789_125897734_Advent Geneva']

Empty DataFrame
Columns: [SideB.ViewData._ID, Actual_Status, ViewData.Age, ViewData.BreakID, AUA_ViewData._ID, ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, combined_flag, 1_repeat_flag, 0_repeat_flag]
Index: []

In [5503]:
aua_id_match3[aua_id_match3['SideB.ViewData._ID'] == '5ee721a315545830acc67099']

Empty DataFrame
Columns: [SideB.ViewData._ID, Actual_Status, ViewData.Age, ViewData.BreakID, AUA_ViewData._ID, ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, combined_flag, 1_repeat_flag, 0_repeat_flag]
Index: []

In [5504]:
aua_id_match3

,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag
0,NaN,UMR,0,1330102496,5ee20f879bbee7249c24fa4e,"846_125880291_Advent Geneva,757_125891404_Adve...","304_125889670_State Street,654_125889670_State...",0,0,0
1,NaN,UCB,0,1328331329,5ee0deaf9bbee72a2895012b,NaN,34_125889670_State Street,0,0,0
2,NaN,UCB,0,1328247629,5ee0deaf9bbee72a2895012a,NaN,264_125893206_State Street,0,0,0
3,5ee0d8c015545825a4c963d0,UMR,0,1328331330,5ee0de3e9bbee72a2894b47b,795_125893206_Advent Geneva,1_125891404_State Street,0,0,0
4,NaN,UCB,0,1328249363,5ee0ddb19bbee72a2894b3b8,NaN,204_125893206_State Street,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1666,5ee0689515545825a4b96fbf,UCB,0,1326538230,5ee08c3e9bbee82088a11d44,1582_125891836_Advent Geneva,NaN,0,0,0
1667,5ee0689515545825a4b95df4,UCB,0,1326533230,5ee08c3e9bbee82088a11d43,1468_125891836_Advent Geneva,NaN,0,0,0
1668,5ee0689515545825a4b96fb1,UCB,0,1326538224,5ee08c3e9bbee82088a11d42,2_125891836_Advent Geneva,NaN,0,0,0
1669,5ee0689515545825a4b95de0,UCB,0,1326533141,5ee08c3e9bbee82088a11d41,788_125891836_Advent Geneva,NaN,0,0,0
1670,5ee0689515545825a4b95dad,UCB,0,1326532665,5ee08c3e9bbee82088a11d40,1581_125891836_Advent Geneva,NaN,0,0,0

In [5505]:
pb_side = X_test.groupby('SideA.ViewData.BreakID_A_side')['Predicted_action'].unique().reset_index()

In [5506]:
pb_side['len'] = pb_side['Predicted_action'].apply(lambda x: len(x))

In [5507]:
pb_side['No_Pair_flag'] = pb_side.apply(lambda x: 1 if 'No-Pair' in x['Predicted_action'] else 0, axis=1)

In [5508]:
pb_side_open_ids = pb_side[(pb_side['len']==1) & (pb_side['No_Pair_flag']==1)]['SideA.ViewData.BreakID_A_side']

In [5509]:
prediction_table3[prediction_table3['SideB.ViewData.BreakID_B_side']=='1335439926']

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID]
Index: []

In [5510]:
aua_id_match3[aua_id_match3['ViewData.Side0_UniqueIds'].isnull()]

,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag
1,NaN,UCB,0,1328331329,5ee0deaf9bbee72a2895012b,NaN,34_125889670_State Street,0,0,0
2,NaN,UCB,0,1328247629,5ee0deaf9bbee72a2895012a,NaN,264_125893206_State Street,0,0,0
4,NaN,UCB,0,1328249363,5ee0ddb19bbee72a2894b3b8,NaN,204_125893206_State Street,0,0,0
5,NaN,UCB,0,1328249362,5ee0ddb19bbee72a2894b3b4,NaN,697_125893206_State Street,0,0,0
6,NaN,UCB,0,1328249357,5ee0ddb19bbee72a2894b3b9,NaN,690_125893206_State Street,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1654,NaN,UCB,0,1326532676,5ee08e9c9bbee82088a1233a,NaN,292_125891836_CITI,0,0,0
1655,NaN,UCB,0,1326538210,5ee08e9c9bbee82088a12339,NaN,1331_125891836_CITI,0,0,0
1658,NaN,UCB,0,1326532706,5ee08e9c9bbee82088a12336,NaN,2039_125891836_CITI,0,0,0
1659,NaN,UCB,0,1326532684,5ee08e9c9bbee82088a12335,NaN,2038_125891836_CITI,0,0,0
1660,NaN,UCB,0,1326532670,5ee08e9c9bbee82088a12334,NaN,291_125891836_CITI,0,0,0

In [5511]:
prediction_table_new = pd.merge(prediction_table3, aua_id_match3, on='SideB.ViewData._ID', how='left')

In [5512]:
prediction_table_new[prediction_table_new['SideB.ViewData.BreakID_B_side'] == '1334352050']

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID, Actual_Status, ViewData.Age, ViewData.BreakID, AUA_ViewData._ID, ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, combined_flag, 1_repeat_flag, 0_repeat_flag]
Index: []

In [5513]:
prediction_table_new[prediction_table_new['Actual_Status']=='OB']

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag
2231,1306562004,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1314644567],NaN,NaN,UMR_One_to_One,[1314644567],1.0,0.984274,0.009003,0.003016,0.003707,5ee08b1f15545830ac5ca09a,5ee08b1f15545830ac5cbca4,OB,13.0,1.306562e+09,5ee0a0ab4333822200af4fdc,1350_125877444_Advent Geneva,NaN,0.0,0.0,0.0
3227,1327140855,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.054548,0.076471,0.031593,0.984538,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c93ee,OB,103.0,1.327141e+09,5ee0a0ab4333822200af4f8b,3767_125762614_Advent Geneva,NaN,0.0,0.0,0.0
3228,1327140857,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.014438,0.010189,0.010703,0.986176,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c93f1,OB,103.0,1.327141e+09,5ee0a0ab4333822200af4f8c,3724_125762614_Advent Geneva,NaN,0.0,0.0,0.0
3229,1327140861,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.014438,0.010189,0.010703,0.986167,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c93f4,OB,103.0,1.327141e+09,5ee0a0ab4333822200af4f90,3725_125762614_Advent Geneva,NaN,0.0,0.0,0.0
3230,1327140870,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.061921,0.046772,0.058832,0.986070,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9410,OB,85.0,1.327141e+09,5ee0a0ab4333822200af4fa8,3937_125785315_Advent Geneva,NaN,0.0,0.0,0.0
3233,1327140875,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,"[1327140663, 1327141099]",NaN,UMT_One_to_One,"[1327140663, 1327141099]",2.0,0.121509,0.235689,0.061070,0.609698,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9418,OB,85.0,1.327141e+09,5ee0a0ab4333822200af4fb1,3936_125785315_Advent Geneva,NaN,0.0,0.0,0.0
3235,1327140880,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.013854,0.010244,0.014294,0.986525,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9413,OB,85.0,1.327141e+09,5ee0a0ab4333822200af4fa6,3944_125785315_Advent Geneva,NaN,0.0,0.0,0.0
3241,1327140956,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.115944,0.351606,0.128288,0.940646,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9426,OB,70.0,1.327141e+09,5ee0a0ab4333822200af4fc3,1058_125804334_Advent Geneva,NaN,0.0,0.0,0.0
3243,1327140960,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.072905,0.191334,0.133910,0.978873,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9429,OB,70.0,1.327141e+09,5ee0a0ab4333822200af4fc9,1061_125804334_Advent Geneva,NaN,0.0,0.0,0.0
3265,1327141121,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.060676,0.028780,0.047612,0.983838,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9447,OB,82.0,1.327141e+09,5ee0a0ab4333822200af4fdd,4082_125790161_Advent Geneva,NaN,0.0,0.0,0.0
3266,1327141123,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.137808,0.308247,0.066316,0.984875,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9443,OB,82.0,1.327141e+09,5ee0a0ab4333822200af4fc4,4081_125790161_Advent Geneva,NaN,0.0,0.0,0.0
3267,1327141124,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.013854,0.010244,0.014294,0.986437,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9441,OB,86.0,1.327141e+09,5ee0a0ab4333822200af4fcc,2994_125783607_Advent Geneva,NaN,0.0,0.0,0.0
3268,1327141125,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.021170,0.019495,0.028294,0.984406,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9446,OB,82.0,1.327141e+09,5ee0a0ab4333822200af4fcb,4080_125790161_Advent Geneva,NaN,0.0,0.0,0.0

In [5514]:
aua_id_match4 = aua_id_match3.rename(columns = {'ViewData.BreakID': 'SideB.ViewData.BreakID_B_side'})
aua_id_match4 = aua_id_match4.rename(columns = {'Actual_Status': 'Actual_Status_Open'})

In [5515]:
aua_id_match4['SideB.ViewData.BreakID_B_side'] = aua_id_match4['SideB.ViewData.BreakID_B_side'].astype(str)

In [5516]:
#prediction_table_new = pd.merge(prediction_table_new ,aua_open_status, on='SideB.ViewData.BreakID_B_side', how='left')
prediction_table_new = pd.merge(prediction_table_new ,aua_id_match4[['SideB.ViewData.BreakID_B_side','Actual_Status_Open']], on='SideB.ViewData.BreakID_B_side', how='left')

In [5517]:
#prediction_table_new

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag,Actual_Status_Open
0,952496851,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.105910,0.176388,0.129583,0.954913,5ee072861554582814141bd6,5ee072861554582814140ed1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,959509436,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.075652,0.134378,0.135453,0.951449,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,967115733,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,"[1327140659, 1327141078]",NaN,UMT_One_to_One,"[1327140659, 1327141078]",2.0,0.208124,0.163815,0.152302,0.487354,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,967115815,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.160135,0.770441,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,967115839,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.143237,0.931756,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3643,1329848340,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329848346],NaN,UMT_One_to_One,[1329848346],1.0,0.170127,0.341575,0.159862,0.328436,5ee1f34a1554582814566bca,5ee1f34a1554582814566f48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3644,1329848341,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.009869,0.007887,0.007430,0.986733,5ee1f34a1554582814566bca,5ee1f34a1554582814566f46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3645,1329848342,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.010880,0.008551,0.009224,0.979510,5ee1f34a1554582814566f87,5ee1f34a1554582814566f4a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3646,1329848343,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329847179],NaN,UMT_One_to_One,[1329847179],1.0,0.122482,0.396144,0.050465,0.430908,5ee1f34a1554582814566bca,5ee1f34a1554582814566f4c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3647,1329848347,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.005779,0.004466,0.003528,0.989149,5ee1f34a1554582814566bcb,5ee1f34a1554582814566f55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5518]:
prediction_table_new[prediction_table_new['Actual_Status_Open']=='OB']['Final_prediction'].value_counts()

No-Pair           258
UMT_One_to_One     63
UMR_One_to_One      7
Name: Final_prediction, dtype: int64

In [5519]:
prediction_table_new.loc[prediction_table_new['Final_prediction']=='No-Pair/Unrecognized','Final_prediction'] = 'No-Pair'

In [5520]:
prediction_table_new.loc[prediction_table_new['Actual_Status'].isnull()]

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag,Actual_Status_Open
0,952496851,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.105910,0.176388,0.129583,0.954913,5ee072861554582814141bd6,5ee072861554582814140ed1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,959509436,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.075652,0.134378,0.135453,0.951449,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,967115733,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,"[1327140659, 1327141078]",NaN,UMT_One_to_One,"[1327140659, 1327141078]",2.0,0.208124,0.163815,0.152302,0.487354,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,967115815,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.160135,0.770441,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,967115839,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.261958,0.143237,0.931756,5ee08b1f15545830ac5ca215,5ee08b1f15545830ac5c9648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3643,1329848340,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329848346],NaN,UMT_One_to_One,[1329848346],1.0,0.170127,0.341575,0.159862,0.328436,5ee1f34a1554582814566bca,5ee1f34a1554582814566f48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3644,1329848341,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.009869,0.007887,0.007430,0.986733,5ee1f34a1554582814566bca,5ee1f34a1554582814566f46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3645,1329848342,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.010880,0.008551,0.009224,0.979510,5ee1f34a1554582814566f87,5ee1f34a1554582814566f4a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3646,1329848343,"[No-Pair, UMT_One_to_One]",2,1,0,1,0,NaN,[1329847179],NaN,UMT_One_to_One,[1329847179],1.0,0.122482,0.396144,0.050465,0.430908,5ee1f34a1554582814566bca,5ee1f34a1554582814566f4c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3647,1329848347,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.005779,0.004466,0.003528,0.989149,5ee1f34a1554582814566bcb,5ee1f34a1554582814566f55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5521]:
prediction_table_new.loc[~prediction_table_new['Actual_Status_Open'].isnull(),'Actual_Status'] = prediction_table_new.loc[~prediction_table_new['Actual_Status_Open'].isnull(),'Actual_Status_Open']

In [5522]:
prediction_table_new.loc[~prediction_table_new['Actual_Status_Open'].isnull(),:]

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag,Actual_Status_Open
23,1089527527,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.080689,0.135735,0.150492,0.971552,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c96bc,OB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OB
24,1089527528,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.072348,0.041065,0.063965,0.980092,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c96a1,OB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OB
25,1089527529,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.430618,0.152823,0.809368,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c9687,OB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OB
26,1089527531,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.192598,0.430618,0.148918,0.802169,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c9657,OB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OB
106,1127396672,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.194870,0.213129,0.156496,0.964417,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c9e52,OB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3615,1327466917,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.007533,0.005360,0.003854,0.987856,5ee0a35a15545828142ed36a,5ee0a35a15545828142ed3a9,UCB,0.0,1.327467e+09,5ee0ae1c9bbee72a2892e513,36_125892699_Advent Geneva,NaN,0.0,0.0,0.0,UCB
3617,1327511387,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.011389,0.008220,0.005998,0.982986,5ee0a8ba15545828142f4788,5ee0a8ba15545828142f4797,UCB,0.0,1.327511e+09,5ee0abaf4333822200afcd5a,22_125892781_Advent Geneva,NaN,0.0,0.0,0.0,UCB
3618,1327511390,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.007440,0.005868,0.006328,0.986251,5ee0a8ba15545828142f4788,5ee0a8ba15545828142f479a,UCB,0.0,1.327511e+09,5ee0abaf4333822200afcd59,23_125892781_Advent Geneva,NaN,0.0,0.0,0.0,UCB
3633,1328247631,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.008501,0.006046,0.005127,0.985769,5ee0d8c015545825a4c96980,5ee0d8c015545825a4c963d4,UCB,0.0,1.328248e+09,5ee0ddb19bbee72a2894b399,794_125893206_Advent Geneva,NaN,0.0,0.0,0.0,UCB
3634,1328249346,[No-Pair],1,1,0,0,0,NaN,NaN,NaN,No-Pair,NaN,NaN,0.008769,0.007654,0.010076,0.985337,5ee0d8c015545825a4c96980,5ee0d8c015545825a4c96981,UCB,0.0,1.328249e+09,5ee0ddb19bbee72a2894b3a6,793_125893206_Advent Geneva,NaN,0.0,0.0,0.0,UCB

In [5523]:
prediction_table_new[prediction_table_new['SideB.ViewData.BreakID_B_side'] =='1334352248']

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID, Actual_Status, ViewData.Age, ViewData.BreakID, AUA_ViewData._ID, ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, combined_flag, 1_repeat_flag, 0_repeat_flag, Actual_Status_Open]
Index: []

In [5524]:
prediction_table_new.loc[prediction_table_new['Actual_Status']=='OB','Actual_Status'] = 'Open Break'

In [5525]:
prediction_table_new.loc[prediction_table_new['Final_prediction']=='No-Pair','Final_prediction'] = 'Open Break'
prediction_table_new.loc[prediction_table_new['Final_prediction']=='UMR_One_to_One','Final_prediction'] = 'UMR'
prediction_table_new.loc[prediction_table_new['Final_prediction']=='UMT_One_to_One','Final_prediction'] = 'UMT'
prediction_table_new.loc[prediction_table_new['Final_prediction']=='UMB_One_to_One','Final_prediction'] = 'UMB'

In [5526]:
prediction_table_new['Actual_Status'].isnull().sum()

2760

In [5527]:
prediction_table_new = prediction_table_new[~prediction_table_new['Actual_Status'].isnull()]
prediction_table_new = prediction_table_new.reset_index()
prediction_table_new = prediction_table_new.drop('index',1)

## Final Actual vs Predicted Table - Process Initiation

In [5528]:
meo = pd.read_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/MEO/MeoCollections.MEO_HST_RecData_125_2020-06-8.csv",usecols=new_cols)

In [5529]:
meo = meo[['ViewData.BreakID','ViewData.Side1_UniqueIds','ViewData.Side0_UniqueIds','ViewData.Age','ViewData.Status']].drop_duplicates()

In [5530]:
meo['key'] = meo['ViewData.Side0_UniqueIds'].astype(str) + meo['ViewData.Side1_UniqueIds'].astype(str)

In [5531]:
aua_id_match5 = aua_id_match3.rename(columns ={'Actual_Status': 'ViewData.Status'})

In [5532]:
aua_sub = aua_id_match5[['ViewData.Side1_UniqueIds','ViewData.Side0_UniqueIds','ViewData.Age','ViewData.Status']].drop_duplicates()

In [5533]:
aua_sub['key'] = aua_sub['ViewData.Side0_UniqueIds'].astype(str) + aua_sub['ViewData.Side1_UniqueIds'].astype(str)

In [5534]:
prediction_table_new['ViewData.BreakID'] = prediction_table_new['SideB.ViewData.BreakID_B_side']
prediction_table_new['ViewData.BreakID'] = prediction_table_new['ViewData.BreakID'].astype(str)

In [5535]:
meo['ViewData.BreakID'] = meo['ViewData.BreakID'].astype(str)

In [5536]:
prediction_table_new1 = pd.merge(prediction_table_new, meo[['ViewData.BreakID','key']], on='ViewData.BreakID', how='left')

In [5537]:
prediction_table_new1[prediction_table_new1['Final_prediction']=='UMR']

,SideB.ViewData.BreakID_B_side,Predicted_action,len,No_Pair_flag,UMB_flag,UMT_flag,UMR_flag,Predicted_UMR_array,Predicted_UMT_array,Predicted_UMB_array,Final_prediction,Final_predicted_break,predicted_break_len,probability_UMR,probability_UMT,probability_UMB,probability_No_pair,SideA.ViewData._ID,SideB.ViewData._ID,Actual_Status,ViewData.Age,ViewData.BreakID,AUA_ViewData._ID,ViewData.Side0_UniqueIds,ViewData.Side1_UniqueIds,combined_flag,1_repeat_flag,0_repeat_flag,Actual_Status_Open,key
10,1207340065,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1125274450],NaN,NaN,UMR,[1125274450],1.0,0.975472,0.008010,0.002535,0.013982,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c9a39,Open Break,NaN,1207340065,NaN,NaN,NaN,NaN,NaN,NaN,OB,1389_125800799_Advent Genevanan
30,1246192436,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1193549304],NaN,NaN,UMR,[1193549304],1.0,0.980651,0.006954,0.001898,0.010498,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c95a9,Open Break,NaN,1246192436,NaN,NaN,NaN,NaN,NaN,NaN,OB,729_125831128_Advent Genevanan
125,1255075932,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1135673821],NaN,NaN,UMR,[1135673821],1.0,0.957751,0.013517,0.004665,0.024067,5ee08b1f15545830ac5ca411,5ee08b1f15545830ac5c962e,Open Break,NaN,1255075932,NaN,NaN,NaN,NaN,NaN,NaN,OB,1043_125838157_Advent Genevanan
159,1306562004,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1314644567],NaN,NaN,UMR,[1314644567],1.0,0.984274,0.009003,0.003016,0.003707,5ee08b1f15545830ac5ca09a,5ee08b1f15545830ac5cbca4,Open Break,13.0,1306562004,5ee0a0ab4333822200af4fdc,1350_125877444_Advent Geneva,NaN,0.0,0.0,0.0,OB,1350_125877444_Advent Genevanan
160,1323773607,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1328247546],NaN,NaN,UMR,[1328247546],1.0,0.985652,0.007564,0.002507,0.004276,5ee0d8c015545825a4c96980,5ee0d8c015545825a4c963b8,UMR,0.0,1323773607,5ee0daa39bbee72a2894a003,445_125889670_Advent Geneva,261_125893206_State Street,0.0,0.0,0.0,NaN,445_125889670_Advent Genevanan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1327615578,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1327615571],NaN,NaN,UMR,[1327615571],1.0,0.984251,0.007777,0.003244,0.004728,5ee0bb8d15545825a4c7c2ad,5ee0bb8d15545825a4c7c2be,UMR,0.0,1327615578,5ee0bd649bbee72a2893cd54,12_125892987_Advent Geneva,8_125892987_Northern Trust,0.0,0.0,0.0,NaN,12_125892987_Advent Genevanan
881,1327615579,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1327615584],NaN,NaN,UMR,[1327615584],1.0,0.985651,0.006863,0.003043,0.004443,5ee0bb8d15545825a4c7c2ad,5ee0bb8d15545825a4c7c2bf,UMR,0.0,1327615579,5ee0bd659bbee72a2893cdcc,3_125892987_Advent Geneva,11_125892987_Northern Trust,0.0,0.0,0.0,NaN,3_125892987_Advent Genevanan
882,1327615580,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1327615575],NaN,NaN,UMR,[1327615575],1.0,0.985651,0.006863,0.003043,0.004443,5ee0bb8d15545825a4c7c2ad,5ee0bb8d15545825a4c7c2c0,UMR,0.0,1327615580,5ee0bd649bbee72a2893cd84,6_125892987_Advent Geneva,10_125892987_Northern Trust,0.0,0.0,0.0,NaN,6_125892987_Advent Genevanan
883,1327615586,"[No-Pair, UMR_One_to_One]",2,1,0,0,1,[1327615585],NaN,NaN,UMR,[1327615585],1.0,0.984822,0.007538,0.003112,0.004528,5ee0bb8d15545825a4c7c2ad,5ee0bb8d15545825a4c7c2c8,UMR,0.0,1327615586,5ee0bd669bbee72a2893cde4,10_125892987_Advent Geneva,5_125892987_Northern Trust,0.0,0.0,0.0,NaN,10_125892987_Advent Genevanan
885,1328247620,[UMR_One_to_One],1,0,0,0,1,[1325919010],NaN,NaN,UMR,[1325919010],1.0,0.977957,0.007497,0.002616,0.011930,5ee0d8c015545825a4c963bf,5ee0d8c015545825a4c963d0,UMR,0.0,1328247620,5ee0de3e9bbee72a2894b47b,795_125893206_Advent Geneva,1_125891404_State Street,0.0,0.0,0.0,NaN,795_125893206_Advent Genevanan

In [5538]:
prediction_table_new1[prediction_table_new1['ViewData.Side0_UniqueIds']=='789_125897734_Advent Geneva']

Empty DataFrame
Columns: [SideB.ViewData.BreakID_B_side, Predicted_action, len, No_Pair_flag, UMB_flag, UMT_flag, UMR_flag, Predicted_UMR_array, Predicted_UMT_array, Predicted_UMB_array, Final_prediction, Final_predicted_break, predicted_break_len, probability_UMR, probability_UMT, probability_UMB, probability_No_pair, SideA.ViewData._ID, SideB.ViewData._ID, Actual_Status, ViewData.Age, ViewData.BreakID, AUA_ViewData._ID, ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, combined_flag, 1_repeat_flag, 0_repeat_flag, Actual_Status_Open, key]
Index: []

In [5539]:
aua_sub1 = pd.merge(aua_sub, prediction_table_new1[['key','Final_prediction','probability_UMR','probability_No_pair','probability_UMT','probability_UMB','Final_predicted_break']], on='key', how='left')

In [5540]:
aua_sub1[aua_sub1['ViewData.Side0_UniqueIds']=='789_125897734_Advent Geneva']

Empty DataFrame
Columns: [ViewData.Side1_UniqueIds, ViewData.Side0_UniqueIds, ViewData.Age, ViewData.Status, key, Final_prediction, probability_UMR, probability_No_pair, probability_UMT, probability_UMB, Final_predicted_break]
Index: []

In [5541]:
no_open = prediction_table_new1[prediction_table_new1['Final_prediction']!='Open Break'].reset_index()
no_open = no_open.drop('index',1)

no_open['key'] = no_open['ViewData.Side0_UniqueIds'].astype(str) + no_open['ViewData.Side1_UniqueIds'].astype(str)

In [5542]:
#aua_sub1[aua_sub1['Final_prediction']=='UMR_One_to_One']
X_test['key'] = X_test['SideB.ViewData.Side0_UniqueIds'].astype(str) + X_test['SideA.ViewData.Side1_UniqueIds'].astype(str)

In [5543]:
aua_sub[aua_sub['ViewData.Side0_UniqueIds'] == '789_125897734_Advent Geneva']

Empty DataFrame
Columns: [ViewData.Side1_UniqueIds, ViewData.Side0_UniqueIds, ViewData.Age, ViewData.Status, key]
Index: []

In [5544]:
aua_sub = pd.merge(aua_sub1, no_open[['key','Final_prediction']], on='key', how='left')

In [5545]:
aua_sub11 = aua_sub1[aua_sub1['Final_prediction']=='Open Break']
aua_sub11 = aua_sub11.reset_index()
aua_sub11 = aua_sub11.drop('index',1)

In [5546]:
aua_sub11['probability_UMR'].fillna(0.00355,inplace=True)
aua_sub11['probability_UMB'].fillna(0.003124,inplace=True)
aua_sub11['probability_UMT'].fillna(0.00255,inplace=True)
aua_sub11['probability_No_pair'].fillna(0.99034,inplace=True)

In [5547]:
aua_sub22 = aua_sub1[aua_sub1['Final_prediction']!='Open Break'][['ViewData.Side1_UniqueIds', 'ViewData.Side0_UniqueIds', 'ViewData.Age','ViewData.Status', 'key']]

aua_sub22 = aua_sub22.reset_index()
aua_sub22 = aua_sub22.drop('index',1)
aua_sub22 = pd.merge(aua_sub22, no_open[['key','Final_prediction','probability_UMR','probability_No_pair','probability_UMT','probability_UMB','Final_predicted_break']], on='key', how='left')
aua_sub22 = aua_sub22.reset_index()
aua_sub22 = aua_sub22.drop('index',1)

In [5548]:
aua_sub33 = pd.concat([aua_sub11,aua_sub22], axis=0)
aua_sub33 = aua_sub33.reset_index()
aua_sub33 = aua_sub33.drop('index',1)

In [5549]:
aua_sub33['ViewData.Side0_UniqueIds'] = aua_sub33['ViewData.Side0_UniqueIds'].astype(str)
aua_sub33['ViewData.Side1_UniqueIds'] = aua_sub33['ViewData.Side1_UniqueIds'].astype(str)

In [5550]:
aua_sub33['len_side0'] = aua_sub33.apply(lambda x: len(x['ViewData.Side0_UniqueIds'].split(',')), axis=1)
aua_sub33['len_side1'] = aua_sub33.apply(lambda x: len(x['ViewData.Side1_UniqueIds'].split(',')), axis=1)

In [5551]:
aua_sub33.loc[(aua_sub33['len_side0']>1) & (aua_sub33['len_side1']==1) & (aua_sub33['ViewData.Status']=='OB') ,'Type'] = 'One_side_aggregation'
aua_sub33.loc[(aua_sub33['len_side0']>1) & (aua_sub33['len_side1']==1) & (aua_sub33['ViewData.Status']!='OB') ,'Type'] = 'One_to_Many'

aua_sub33.loc[(aua_sub33['len_side0']==1) & (aua_sub33['len_side1']>1) & (aua_sub33['ViewData.Status']=='OB') ,'Type'] = 'One_side_aggregation'
aua_sub33.loc[(aua_sub33['len_side0']==1) & (aua_sub33['len_side1']>1) & (aua_sub33['ViewData.Status']!='OB') ,'Type'] = 'One_to_Many'
aua_sub33.loc[(aua_sub33['len_side0']>1) & (aua_sub33['len_side1']>1) & (aua_sub33['ViewData.Status']!='OB') ,'Type'] = 'Many_to_Many'

aua_sub33.loc[(aua_sub33['len_side0']==1) & (aua_sub33['len_side1']==1) ,'Type'] = 'One_to_One/Open'

In [5552]:
aua_sub44 = aua_sub33[(aua_sub33['ViewData.Status']=='UMB') & (aua_sub33['ViewData.Age']>1)]
aua_sub44 = aua_sub44.reset_index()
aua_sub44 = aua_sub44.drop('index',1)

In [5553]:
aua_sub44['Final_prediction'].fillna('UMB-Carry-Forward',inplace= True)
aua_sub44['probability_UMR'].fillna(0.0001,inplace= True)
aua_sub44['probability_UMB'].fillna(0.9998,inplace= True)
aua_sub44['probability_UMT'].fillna(0.0000,inplace= True)
aua_sub44['probability_No_pair'].fillna(0.0000,inplace= True)

Series([], Name: probability_No_pair, dtype: float64)

In [5554]:
aua_sub55 = aua_sub33[~((aua_sub33['ViewData.Status']=='UMB') & (aua_sub33['ViewData.Age']>1))]
aua_sub55 = aua_sub55.reset_index()
aua_sub55 = aua_sub55.drop('index',1)

In [5555]:
aua_sub66 = pd.concat([aua_sub55,aua_sub44], axis=0)
aua_sub66 = aua_sub66.reset_index()
aua_sub66 = aua_sub66.drop('index',1)

In [5556]:
aua_sub66.loc[(aua_sub66['ViewData.Status']=='UMB') & (aua_sub66['ViewData.Age']>1),'ViewData.Status'] = 'UMB-Carry-Forward'
aua_sub66.loc[(aua_sub66['ViewData.Status']=='OB'),'ViewData.Status'] = 'Open Break'

In [5557]:
aua_sub66

,ViewData.Side1_UniqueIds,ViewData.Side0_UniqueIds,ViewData.Age,ViewData.Status,key,Final_prediction,probability_UMR,probability_No_pair,probability_UMT,probability_UMB,Final_predicted_break,len_side0,len_side1,Type
0,nan,793_125893206_Advent Geneva,0,UCB,793_125893206_Advent Genevanan,Open Break,0.008769,0.985337,0.007654,0.010076,NaN,1,1,One_to_One/Open
1,nan,794_125893206_Advent Geneva,0,UCB,794_125893206_Advent Genevanan,Open Break,0.008501,0.985769,0.006046,0.005127,NaN,1,1,One_to_One/Open
2,nan,22_125892781_Advent Geneva,0,UCB,22_125892781_Advent Genevanan,Open Break,0.011389,0.982986,0.008220,0.005998,NaN,1,1,One_to_One/Open
3,nan,23_125892781_Advent Geneva,0,UCB,23_125892781_Advent Genevanan,Open Break,0.007440,0.986251,0.005868,0.006328,NaN,1,1,One_to_One/Open
4,nan,7_125892699_Advent Geneva,1,Open Break,7_125892699_Advent Genevanan,Open Break,0.003708,0.990837,0.002476,0.002979,NaN,1,1,One_to_One/Open
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1668,nan,1582_125891836_Advent Geneva,0,UCB,1582_125891836_Advent Genevanan,NaN,NaN,NaN,NaN,NaN,NaN,1,1,One_to_One/Open
1669,nan,1468_125891836_Advent Geneva,0,UCB,1468_125891836_Advent Genevanan,NaN,NaN,NaN,NaN,NaN,NaN,1,1,One_to_One/Open
1670,nan,2_125891836_Advent Geneva,0,UCB,2_125891836_Advent Genevanan,NaN,NaN,NaN,NaN,NaN,NaN,1,1,One_to_One/Open
1671,nan,788_125891836_Advent Geneva,0,UCB,788_125891836_Advent Genevanan,NaN,NaN,NaN,NaN,NaN,NaN,1,1,One_to_One/Open
1672,nan,1581_125891836_Advent Geneva,0,UCB,1581_125891836_Advent Genevanan,NaN,NaN,NaN,NaN,NaN,NaN,1,1,One_to_One/Open

## Read No-Pair Id File

In [5558]:
no_pair_id_data = pd.read_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/X_Test/no_pair_ids_125_2020-06-8.csv")

In [5559]:
no_pair_ids = no_pair_id_data['filter_key'].unique()

In [5560]:
aua_sub66.loc[aua_sub66['ViewData.Side1_UniqueIds'].isin(no_pair_ids),'Final_prediction'] = aua_sub66.loc[aua_sub66['ViewData.Side1_UniqueIds'].isin(no_pair_ids),'ViewData.Status']
aua_sub66.loc[aua_sub66['ViewData.Side0_UniqueIds'].isin(no_pair_ids),'Final_prediction'] = aua_sub66.loc[aua_sub66['ViewData.Side0_UniqueIds'].isin(no_pair_ids),'ViewData.Status']

In [5561]:
aua_sub66['Type'].value_counts()

One_to_One/Open    1623
One_to_Many          37
Many_to_Many         13
Name: Type, dtype: int64

In [5672]:
#aua_sub66

In [5563]:
pb_side_grp = X_test.groupby(['SideA.ViewData.Side1_UniqueIds'])['Predicted_action'].unique().reset_index()

In [5564]:
pb_side_grp

     SideA.ViewData.Side1_UniqueIds           Predicted_action
0     1000_125691779_Morgan Stanley                  [No-Pair]
1      1000_125738158_Goldman Sachs                  [No-Pair]
2      1000_125888227_Goldman Sachs                  [No-Pair]
3     1000_125890550_Morgan Stanley                  [No-Pair]
4     1001_125691779_Morgan Stanley  [No-Pair, UMT_One_to_One]
...                             ...                        ...
5035           9_125888606_Barclays                  [No-Pair]
5036          9_125890198_JP Morgan                  [No-Pair]
5037           9_125892165_Barclays                  [No-Pair]
5038          9_125892781_JP Morgan                  [No-Pair]
5039     9_125892987_Northern Trust  [No-Pair, UMR_One_to_One]

[5040 rows x 2 columns]

In [5565]:
pb_side_grp_status = X_test.groupby(['SideA.ViewData.Side1_UniqueIds'])['SideA.ViewData.Status'].unique().reset_index()
pb_side_grp_status['SideA.ViewData.Status'] = pb_side_grp_status['SideA.ViewData.Status'].apply(lambda x: str(x).replace("[",""))
pb_side_grp_status['SideA.ViewData.Status'] = pb_side_grp_status['SideA.ViewData.Status'].apply(lambda x: str(x).replace("]",""))
pb_side_grp['len'] = pb_side_grp.apply(lambda x: len(x['Predicted_action']), axis=1)
pb_side_grp['No_pair_flag'] = pb_side_grp.apply(lambda x: 1 if x['len'] == 1 and "No-Pair" in x['Predicted_action'] else 0, axis=1)

In [5566]:
pb_side_grp = pd.merge(pb_side_grp,pb_side_grp_status, on='SideA.ViewData.Side1_UniqueIds', how='left')

In [5567]:
#pb_side_grp['SideA.ViewData.Status'].value_counts()

In [5568]:
#pb_side_grp = pd.merge(pb_side_grp,pb_side_grp_status, on='SideA.ViewData.Side1_UniqueIds', how='left')
pb_side_grp['Final_status'] = pb_side_grp.apply(lambda x: "Open Break" if x['SideA.ViewData.Status']=="'OB'" else("SDB" if x['SideA.ViewData.Status']=="'SDB'" else "NA"),axis=1)
pb_side_grp = pb_side_grp.rename(columns = {'SideA.ViewData.Side1_UniqueIds':'ViewData.Side1_UniqueIds'})



pb_side_grp1 = pb_side_grp[pb_side_grp['No_pair_flag']==1]
pb_side_grp1 = pb_side_grp1.reset_index()
pb_side_grp1 = pb_side_grp1.drop('index',1)

In [5569]:
aua_sub77 = pd.merge(aua_sub66 ,pb_side_grp1[['ViewData.Side1_UniqueIds','Final_status']], on ='ViewData.Side1_UniqueIds',how='left')

In [5570]:
aua_sub77.loc[(~aua_sub77['Final_status'].isnull()) & (aua_sub77['ViewData.Side0_UniqueIds']=='nan'),'Final_prediction'] = aua_sub77.loc[(~aua_sub77['Final_status'].isnull()) & (aua_sub77['ViewData.Side0_UniqueIds']=='nan'),'Final_status']

In [5571]:
pb_side_grp_B = X_test.groupby(['SideB.ViewData.Side0_UniqueIds'])['Predicted_action'].unique().reset_index()

In [5572]:
pb_side_grp_B_status = X_test.groupby(['SideB.ViewData.Side0_UniqueIds'])['SideB.ViewData.Status'].unique().reset_index()
pb_side_grp_B_status['SideB.ViewData.Status'] = pb_side_grp_B_status['SideB.ViewData.Status'].apply(lambda x: str(x).replace("[",""))
pb_side_grp_B_status['SideB.ViewData.Status'] = pb_side_grp_B_status['SideB.ViewData.Status'].apply(lambda x: str(x).replace("]",""))
pb_side_grp_B['len'] = pb_side_grp_B.apply(lambda x: len(x['Predicted_action']), axis=1)
pb_side_grp_B['No_pair_flag'] = pb_side_grp_B.apply(lambda x: 1 if x['len'] == 1 and "No-Pair" in x['Predicted_action'] else 0, axis=1)

In [5573]:
pb_side_grp_B = pd.merge(pb_side_grp_B,pb_side_grp_B_status, on='SideB.ViewData.Side0_UniqueIds', how='left')
pb_side_grp_B['Final_status_B'] = pb_side_grp_B.apply(lambda x: "Open Break" if x['SideB.ViewData.Status']=="'OB'" else("SDB" if x['SideB.ViewData.Status']=="'SDB'" else "NA"),axis=1)
pb_side_grp_B = pb_side_grp_B.rename(columns = {'SideB.ViewData.Side0_UniqueIds':'ViewData.Side0_UniqueIds'})



pb_side_grp2 = pb_side_grp_B[pb_side_grp_B['No_pair_flag']==1]
pb_side_grp2 = pb_side_grp2.reset_index()
pb_side_grp2 = pb_side_grp2.drop('index',1)

In [5574]:
aua_sub88 = pd.merge(aua_sub77 ,pb_side_grp2[['ViewData.Side0_UniqueIds','Final_status_B']], on ='ViewData.Side0_UniqueIds',how='left')

In [5575]:
aua_sub88.loc[(~aua_sub88['Final_status_B'].isnull()) & (aua_sub88['ViewData.Side1_UniqueIds']=='nan'),'Final_prediction'] = aua_sub88.loc[(~aua_sub88['Final_status_B'].isnull()) & (aua_sub88['ViewData.Side1_UniqueIds']=='nan'),'Final_status_B']

In [5576]:
aua_sub99 = aua_sub88[(aua_sub88['ViewData.Status']!='SDB')]
aua_sub99 = aua_sub99.reset_index()
aua_sub99 = aua_sub99.drop('index',1)

In [5577]:
aua_sub99['Final_prediction'] = aua_sub99['Final_prediction'].fillna('Open Break')
aua_sub99 = aua_sub99.reset_index()
aua_sub99 = aua_sub99.drop('index',1)

In [5578]:
aua_sub99['ViewData.Status'] = aua_sub99['ViewData.Status'].astype(str)
aua_sub99['Final_prediction'] = aua_sub99['Final_prediction'].astype(str)

In [5579]:
#X_test
aua_sub[aua_sub['ViewData.Side0_UniqueIds']=='789_125897734_Advent Geneva']

Empty DataFrame
Columns: [ViewData.Side1_UniqueIds, ViewData.Side0_UniqueIds, ViewData.Age, ViewData.Status, key, Final_prediction_x, probability_UMR, probability_No_pair, probability_UMT, probability_UMB, Final_predicted_break, Final_prediction_y]
Index: []

In [5580]:
#aua[aua['ViewData.Side0_UniqueIds'] == '789_125897734_Advent Geneva']

## Summary file

In [5581]:
break_id_merge = meo[meo['ViewData.Status'].isin(['OB','SDB','UOB','UDB','SPM'])][['ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds','ViewData.BreakID']].drop_duplicates()
break_id_merge = break_id_merge.reset_index()
break_id_merge = break_id_merge.drop('index',1)

In [5582]:
break_id_merge

          ViewData.Side0_UniqueIds ViewData.Side1_UniqueIds ViewData.BreakID
0                              NaN    138_125894481_US BANK       1329848348
1      358_125894481_Advent Geneva                      NaN       1329848347
2                              NaN     18_125894481_US BANK       1329848346
3      495_125894481_Advent Geneva                      NaN       1329848345
4      254_125894481_Advent Geneva                      NaN       1329848344
...                            ...                      ...              ...
8583                           NaN      1651_125891836_CITI       1326535083
8584  1270_125891836_Advent Geneva                      NaN       1326535069
8585                           NaN      1379_125891836_CITI       1326533601
8586                           NaN      1376_125891836_CITI       1326533598
8587  1095_125891836_Advent Geneva                      NaN       1326533579

[8588 rows x 3 columns]

In [5583]:
break_id_merge['key'] = break_id_merge['ViewData.Side0_UniqueIds'].astype(str) + break_id_merge['ViewData.Side1_UniqueIds'].astype(str)

In [5584]:
final = pd.merge(aua_sub99,break_id_merge[['key','ViewData.BreakID']], on='key', how='left')

In [5585]:
aua_sub[aua_sub['ViewData.Side1_UniqueIds']=='233_125897734_Morgan Stanley']

Empty DataFrame
Columns: [ViewData.Side1_UniqueIds, ViewData.Side0_UniqueIds, ViewData.Age, ViewData.Status, key, Final_prediction_x, probability_UMR, probability_No_pair, probability_UMT, probability_UMB, Final_predicted_break, Final_prediction_y]
Index: []

In [5586]:
break_id_merge[break_id_merge['ViewData.BreakID']=='1334352248']

Empty DataFrame
Columns: [ViewData.Side0_UniqueIds, ViewData.Side1_UniqueIds, ViewData.BreakID, key]
Index: []

In [5587]:
break_id_merge.dtypes

ViewData.Side0_UniqueIds    object
ViewData.Side1_UniqueIds    object
ViewData.BreakID            object
key                         object
dtype: object

In [5588]:
#final[final['ViewData.BreakID'].isnull()]

final = pd.merge(final,break_id_merge[['ViewData.Side0_UniqueIds','ViewData.BreakID']], on='ViewData.Side0_UniqueIds', how='left')

In [5589]:
final.loc[final['ViewData.BreakID_x'].isnull(),'ViewData.BreakID_x'] = final.loc[final['ViewData.BreakID_x'].isnull(),'ViewData.BreakID_y']

In [5590]:
final = final.rename(columns={'ViewData.BreakID_x':'ViewData.BreakID'})
final = final.drop('ViewData.BreakID_y',1)

In [5591]:
final1 = final[(final['Type']=='One_to_One/Open') & (final['probability_No_pair'].isnull())]
final1 = final1.reset_index()
final1 = final1.drop('index',1)


final2 = final[~((final['Type']=='One_to_One/Open') & (final['probability_No_pair'].isnull()))]
final2 = final2.reset_index()
final2 = final2.drop('index',1)

In [5592]:
final1['probability_UMR'].fillna(0.0024,inplace=True)
final1['probability_UMB'].fillna(0.004124,inplace=True)
final1['probability_UMT'].fillna(0.00155,inplace=True)
final1['probability_No_pair'].fillna(0.9922,inplace=True)

In [5593]:
final3 = pd.concat([final1, final2], axis=0)

In [5594]:
final3['ML_flag'] = final3.apply(lambda x: "ML" if x['Type']=='One_to_One/Open' else "Non-ML", axis=1)

In [5595]:
prediction_cols = ['ViewData.BreakID', 'ViewData.Side1_UniqueIds', 'ViewData.Side0_UniqueIds','ViewData.Age' ,
       'probability_No_pair', 'probability_UMR','probability_UMB', 'probability_UMT',
       'Final_predicted_break', 'Type', 'ML_flag','ViewData.Status', 'Final_prediction']


final4 = final3[prediction_cols]

final4 = final4.rename(columns ={'ViewData.Status':'Actual_Status', 'Final_prediction': 'Predicted_Status'})

In [5596]:
final4[final4['ML_flag']=='ML']

,ViewData.BreakID,ViewData.Side1_UniqueIds,ViewData.Side0_UniqueIds,ViewData.Age,probability_No_pair,probability_UMR,probability_UMB,probability_UMT,Final_predicted_break,Type,ML_flag,Actual_Status,Predicted_Status
0,NaN,34_125889670_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
1,1328247629,264_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
2,1328249363,204_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
3,1328249362,697_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
4,1328249357,690_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,1326734478,1253_125891903_Goldman Sachs,378_125891903_Advent Geneva,0,0.014162,0.971109,0.003208,0.011520,[1326735517],One_to_One/Open,ML,UMR,UMR
844,1326734491,1255_125891903_Goldman Sachs,379_125891903_Advent Geneva,0,0.014162,0.971109,0.003208,0.011520,[1326735496],One_to_One/Open,ML,UMR,UMR
845,1326735489,44_125891903_Goldman Sachs,1757_125891903_Advent Geneva,0,0.006694,0.980953,0.003152,0.009201,[1326735492],One_to_One/Open,ML,UMR,UMR
846,1326735490,865_125850828_Goldman Sachs,183_125891903_Advent Geneva,0,0.008661,0.974471,0.003995,0.012873,[1326731472],One_to_One/Open,ML,UMR,UMR
847,1326735491,842_125849133_Goldman Sachs,546_125891903_Advent Geneva,0,0.015375,0.952950,0.007689,0.023986,[1326731534],One_to_One/Open,ML,UMR,UMR

In [5597]:
#crosstab_table

In [5598]:
NA_status_file = final4[(final4['Type']=='One_to_One/Open') & (final4['Predicted_Status']=='NA')]
NA_status_file = NA_status_file.reset_index()
NA_status_file = NA_status_file.drop('index',1)

In [5599]:
final5 = final4[~((final4['Type']=='One_to_One/Open') & (final4['Predicted_Status']=='NA'))]
final5 = final5.reset_index()
final5 = final5.drop('index',1)

In [5600]:
NA_status_file_A_side = NA_status_file[NA_status_file['ViewData.Side0_UniqueIds']=='nan']
NA_status_file_B_side = NA_status_file[NA_status_file['ViewData.Side1_UniqueIds']=='nan']

In [5601]:
gg = X_test[X_test['SideA.ViewData.BreakID_A_side'].isin(NA_status_file_A_side['ViewData.BreakID'].unique())].groupby(['SideA.ViewData.BreakID_A_side'])['Predicted_action'].unique().reset_index()
gg.columns = ['ViewData.BreakID','Predicted_action']
gg['NA_prediction_A'] = 'Open Break'

kk = X_test[X_test['SideB.ViewData.BreakID_B_side'].isin(NA_status_file_B_side['ViewData.BreakID'].unique())].groupby(['SideB.ViewData.BreakID_B_side'])['Predicted_action'].unique().reset_index()
kk.columns = ['ViewData.BreakID','Predicted_action']
kk['NA_prediction_B'] = 'Open Break'

C:\Users\consultant136\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [5602]:
gg['ViewData.BreakID'] = gg['ViewData.BreakID'].astype(str)
kk['ViewData.BreakID'] = kk['ViewData.BreakID'].astype(str)

In [5603]:
final6 = pd.merge(NA_status_file, gg[['ViewData.BreakID','NA_prediction_A']], on='ViewData.BreakID', how='left')
final6 = pd.merge(final6, kk[['ViewData.BreakID','NA_prediction_B']], on='ViewData.BreakID', how='left')

In [5604]:
final6.loc[final6['NA_prediction_A'].isnull(),'Predicted_Status'] = 'Open Break'
final6.loc[final6['NA_prediction_B'].isnull(),'Predicted_Status'] = 'Open Break'

In [5605]:
final6 = final6.drop(['NA_prediction_A','NA_prediction_B'],1)

In [5606]:
final5[final5['ViewData.Side0_UniqueIds']=='789_125897734_Advent Geneva']

Empty DataFrame
Columns: [ViewData.BreakID, ViewData.Side1_UniqueIds, ViewData.Side0_UniqueIds, ViewData.Age, probability_No_pair, probability_UMR, probability_UMB, probability_UMT, Final_predicted_break, Type, ML_flag, Actual_Status, Predicted_Status]
Index: []

In [5607]:
final7 = pd.concat([final5, final6], axis=0)
final7 = final7.reset_index()
final7 = final7.drop('index',1)

In [5609]:
X_test.head(3)

,SideA.ViewData.B-P Net Amount,SideA.ViewData.Price,SideA.ViewData.Quantity,SideB.ViewData.Accounting Net Amount,SideB.ViewData.Price,SideB.ViewData.Quantity,Trade_Date_match,Settle_Date_match,Amount_diff_2,Trade_date_diff,Settle_date_diff,SideA.ISIN_NA,SideB.ISIN_NA,ViewData.Combined Fund,ViewData.Combined Transaction Type,All_key_nan,new_key_match,SideA.ViewData._ID,SideB.ViewData._ID,SideB.ViewData.Status,SideB.ViewData.BreakID_B_side,SideA.ViewData.Status,SideA.ViewData.BreakID_A_side,SideB.ViewData.Side0_UniqueIds,SideA.ViewData.Side1_UniqueIds,Predicted_action,probability_No_pair,probability_UMB,probability_UMR,probability_UMT,prob_key,key
0,-1597.8,0.0,0.0,6467.41,2.7252,-24.0,0,0,8065.21,-6.0,-7.0,1,1,21031210MS,dsell,1,0,5ee087c515545825a4be191a,5ee087c515545825a4be1a35,OB,1327122452,OB,1314532476,135_125892165_Advent Geneva,8_125883004_Barclays,No-Pair,0.990913,0.001934,0.004297,0.002856,1327122452No-Pair,135_125892165_Advent Geneva8_125883004_Barclays
1,-1597.8,0.0,0.0,2519.01,1.0700,-24.0,0,0,4116.81,-6.0,-7.0,1,1,21031210MS,dsell,1,0,5ee087c515545825a4be191a,5ee087c515545825a4be1a2f,SPM,1327122449,OB,1314532476,137_125892165_Advent Geneva,8_125883004_Barclays,No-Pair,0.990913,0.001934,0.004297,0.002856,1327122449No-Pair,137_125892165_Advent Geneva8_125883004_Barclays
2,-1597.8,0.0,0.0,-21846.45,9.0723,24.0,0,0,-20248.65,-6.0,-7.0,1,1,21031210MS,dbuy,1,0,5ee087c515545825a4be191a,5ee087c515545825a4be1a19,SPM,1327122435,OB,1314532476,132_125892165_Advent Geneva,8_125883004_Barclays,No-Pair,0.991475,0.002427,0.003597,0.002500,1327122435No-Pair,132_125892165_Advent Geneva8_125883004_Barclays

In [5610]:
pair_match = X_test[X_test['Predicted_action']!='No-Pair']
pair_match = pair_match.reset_index()
pair_match = pair_match.drop('index',1)

In [5611]:
pair_match = pair_match[['Predicted_action',
       'probability_No_pair', 'probability_UMB', 'probability_UMR',
       'probability_UMT', 'key']]
pair_match.columns = ['New_Predicted_action',
       'New_probability_No_pair', 'New_probability_UMB', 'New_probability_UMR',
       'New_probability_UMT','key']

In [5612]:
pair_match['New_Predicted_action'] = pair_match['New_Predicted_action'].apply(lambda x: 'UMR' if x=='UMR_One_to_One' else("UMT" if x=='UMT_One_to_One' else("UMB" if x== "UMB_One_to_One" else x)))

In [5613]:
final7['key'] = final7['ViewData.Side0_UniqueIds'].astype(str) + final7['ViewData.Side1_UniqueIds'].astype(str)

In [5614]:
final8 = pd.merge(final7,pair_match, on='key', how='left')

In [5615]:
final8[~final8['New_Predicted_action'].isnull()]['Predicted_Status'].value_counts()

UMR           177
UMT            69
Open Break      8
Name: Predicted_Status, dtype: int64

In [5616]:
final8[~final8['New_Predicted_action'].isnull()]['Actual_Status'].value_counts()

UMR    185
UMT     66
UMB      3
Name: Actual_Status, dtype: int64

In [5617]:
final8[~final8['New_Predicted_action'].isnull()]['New_Predicted_action'].value_counts()

UMR    185
UMT     69
Name: New_Predicted_action, dtype: int64

In [5618]:
final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'Predicted_Status'] = final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'New_Predicted_action']
final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'probability_No_pair'] = final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'New_probability_No_pair']
final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'probability_UMB'] = final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'New_probability_UMB']
final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'probability_UMR'] = final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'New_probability_UMR']
final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'probability_UMT'] = final8.loc[(~final8['New_Predicted_action'].isnull()) & (final8['New_Predicted_action']!= final8['Predicted_Status']),'New_probability_UMT']

In [5619]:
final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMT'),'probability_UMT'] = final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMT'),'New_probability_UMT']
final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMR'),'probability_UMR'] = final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMR'),'New_probability_UMR']
final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMB'),'probability_UMB'] = final8.loc[(final8['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMB'),'New_probability_UMB']

In [5620]:
umr_break_array_match = prediction_table[prediction_table['Final_prediction']=='UMR_One_to_One'][['SideB.ViewData.BreakID_B_side','Final_predicted_break']]
umt_break_array_match = prediction_table[prediction_table['Final_prediction']=='UMT_One_to_One'][['SideB.ViewData.BreakID_B_side','Final_predicted_break']]

umb_break_array_match = prediction_table[prediction_table['Final_prediction']=='UMB_One_to_One'][['SideB.ViewData.BreakID_B_side','Final_predicted_break']]

umr_break_array_match.columns = np.array(['ViewData.BreakID','New_Final_predicted_break_UMR'])
umt_break_array_match.columns = np.array(['ViewData.BreakID','New_Final_predicted_break_UMT'])
umb_break_array_match.columns = np.array(['ViewData.BreakID','New_Final_predicted_break_UMB'])

In [5621]:
#umr_break_array_match['New_Final_predicted_break_UMR'] = umr_break_array_match['New_Final_predicted_break_UMR'].astype(str) 
#umb_break_array_match['New_Final_predicted_break_UMB'] = umb_break_array_match['New_Final_predicted_break_UMB'].astype(str) 
#umt_break_array_match['New_Final_predicted_break_UMT'] = umt_break_array_match['New_Final_predicted_break_UMT'].astype(str)

In [5622]:
final9 = pd.merge(final8, umr_break_array_match, on ='ViewData.BreakID', how='left')
final9 = pd.merge(final9, umt_break_array_match, on ='ViewData.BreakID', how='left')
final9 = pd.merge(final9, umb_break_array_match, on ='ViewData.BreakID', how='left')

In [5623]:
final9.loc[(final9['Final_predicted_break'].isnull()) & (final9['Predicted_Status']=='UMT'),'Final_predicted_break'] = final9.loc[(final9['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMT'),'New_Final_predicted_break_UMT']
final9.loc[(final9['Final_predicted_break'].isnull()) & (final9['Predicted_Status']=='UMR'),'Final_predicted_break'] = final9.loc[(final9['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMR'),'New_Final_predicted_break_UMR']
final9.loc[(final9['Final_predicted_break'].isnull()) & (final9['Predicted_Status']=='UMB'),'Final_predicted_break'] = final9.loc[(final9['Final_predicted_break'].isnull()) & (final8['Predicted_Status']=='UMB'),'New_Final_predicted_break_UMB']

In [5624]:
#final9[(final9['Actual_Status']=='UMB') & (final9['Predicted_Status']=='UMB') & (final9['ML_flag']=='ML')]['Final_predicted_break']

In [5625]:
final9.columns

Index(['ViewData.BreakID', 'ViewData.Side1_UniqueIds',
       'ViewData.Side0_UniqueIds', 'ViewData.Age', 'probability_No_pair',
       'probability_UMR', 'probability_UMB', 'probability_UMT',
       'Final_predicted_break', 'Type', 'ML_flag', 'Actual_Status',
       'Predicted_Status', 'key', 'New_Predicted_action',
       'New_probability_No_pair', 'New_probability_UMB', 'New_probability_UMR',
       'New_probability_UMT', 'New_Final_predicted_break_UMR',
       'New_Final_predicted_break_UMT', 'New_Final_predicted_break_UMB'],
      dtype='object')

In [5626]:
final9 = final9.drop(['key','New_Predicted_action',
       'New_probability_No_pair', 'New_probability_UMB', 'New_probability_UMR',
       'New_probability_UMT','New_Final_predicted_break_UMR',
       'New_Final_predicted_break_UMT', 'New_Final_predicted_break_UMB'], 1)

In [5627]:
final9

,ViewData.BreakID,ViewData.Side1_UniqueIds,ViewData.Side0_UniqueIds,ViewData.Age,probability_No_pair,probability_UMR,probability_UMB,probability_UMT,Final_predicted_break,Type,ML_flag,Actual_Status,Predicted_Status
0,NaN,34_125889670_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
1,1328247629,264_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
2,1328249363,204_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
3,1328249362,697_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
4,1328249357,690_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,1327140870,nan,3937_125785315_Advent Geneva,85,0.986070,0.061921,0.058832,0.046772,NaN,One_to_One/Open,ML,Open Break,Open Break
1639,1327140880,nan,3944_125785315_Advent Geneva,85,0.986525,0.013854,0.014294,0.010244,NaN,One_to_One/Open,ML,Open Break,Open Break
1640,1327140861,nan,3725_125762614_Advent Geneva,103,0.986167,0.014438,0.010703,0.010189,NaN,One_to_One/Open,ML,Open Break,Open Break
1641,1327140857,nan,3724_125762614_Advent Geneva,103,0.986176,0.014438,0.010703,0.010189,NaN,One_to_One/Open,ML,Open Break,Open Break
1642,1327140855,nan,3767_125762614_Advent Geneva,103,0.984538,0.054548,0.031593,0.076471,NaN,One_to_One/Open,ML,Open Break,Open Break

In [5628]:
#final8['Type'].value_counts()

In [5629]:
#meo1 = pd.read_csv("//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/MEO/MeoCollections.MEO_HST_RecData_125_2020-06-8.csv",usecols=new_cols)

In [5630]:
#meo1[meo1['ViewData.Side1_UniqueIds']=='6_125858636_Goldman Sachs']

## Merging columns from the transaction table

In [5631]:
import pandas as pd

cols_to_show = [
'Account Type',
'Accounting Net Amount',
#'Accounting Net Amount Difference',
'Activity Code',
'Age',
'Alt ID 1',
'Asset Type Category',
'Bloomberg_Yellow_Key',
'B-P Net Amount',
#'B-P Net Amount Difference',
#'B-P Net Amount Difference Absolute',
'BreakID',
'Business Date',
'Call Put Indicator',
'Cancel Amount',
'Cancel Flag',
'Commission',
'Currency',
'CUSIP',
'Custodian',
'Custodian Account',
'Department',
'Description',
'ExpiryDate',
'ExternalComment2',
'Fund',
'FX Rate',
'Interest Amount',
'InternalComment2',
'Investment ID',
'Investment Type',
'Is Combined Data',
'ISIN',
'Keys',
'Knowledge Date',
'Mapped Custodian Account',
'Net Amount Difference',
'Non Trade Description',
'OTE Custodian Account',
'OTE Ticker',
'PB Account Numeric',
'Portfolio ID',
'Portolio',
'Price',
'Prime Broker',
'Principal Amount',
'Quantity',
'Sec Fees',
'SEDOL',
'Settle Date',
'Status',
'Strike Price',
'System Comments',
'Ticker',
'Trade Date',
'Trade Expenses',
'Transaction Category',
'Transaction ID',
'Transaction Type',
'Underlying Cusip',
'Underlying Investment ID',
'Underlying ISIN',
'Underlying Sedol',
'Underlying Ticker',
'UserTran1',
'UserTran2',
'Value Date',
] 
add = ['ViewData.Side0_UniqueIds', 'ViewData.Side1_UniqueIds']
viewdata_cols_to_show = ['ViewData.' + x for x in cols_to_show] + add

In [5632]:
meo_final = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/MEO/MeoCollections.MEO_HST_RecData_125_2020-06-8.csv',usecols = viewdata_cols_to_show)
aua_final = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/AUA/AUACollections.AUA_HST_RecData_125_2020-06-8.csv',usecols = viewdata_cols_to_show)

In [5633]:
#final_predictions = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/Final_Predictions_Table_HST_RecData_125_2020-06-1.csv')

In [5634]:
final_predictions = final9.copy()

In [5635]:
#final_predictions.groupby(['Actual_Status'])['Predicted_Status'].value_counts()

In [5636]:
#final_predictions[(final_predictions['Actual_Status'] == 'Open Break') & (final_predictions['Predicted_Status'] == 'UMR')][['ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds']]

In [5637]:
#final_predictions.groupby(['ViewData.Side0_UniqueIds'])['ViewData.Side1_UniqueIds'].value_counts()

In [5638]:
final_predictions

,ViewData.BreakID,ViewData.Side1_UniqueIds,ViewData.Side0_UniqueIds,ViewData.Age,probability_No_pair,probability_UMR,probability_UMB,probability_UMT,Final_predicted_break,Type,ML_flag,Actual_Status,Predicted_Status
0,NaN,34_125889670_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
1,1328247629,264_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
2,1328249363,204_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
3,1328249362,697_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
4,1328249357,690_125893206_State Street,nan,0,0.992200,0.002400,0.004124,0.001550,NaN,One_to_One/Open,ML,UCB,Open Break
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,1327140870,nan,3937_125785315_Advent Geneva,85,0.986070,0.061921,0.058832,0.046772,NaN,One_to_One/Open,ML,Open Break,Open Break
1639,1327140880,nan,3944_125785315_Advent Geneva,85,0.986525,0.013854,0.014294,0.010244,NaN,One_to_One/Open,ML,Open Break,Open Break
1640,1327140861,nan,3725_125762614_Advent Geneva,103,0.986167,0.014438,0.010703,0.010189,NaN,One_to_One/Open,ML,Open Break,Open Break
1641,1327140857,nan,3724_125762614_Advent Geneva,103,0.986176,0.014438,0.010703,0.010189,NaN,One_to_One/Open,ML,Open Break,Open Break
1642,1327140855,nan,3767_125762614_Advent Geneva,103,0.984538,0.054548,0.031593,0.076471,NaN,One_to_One/Open,ML,Open Break,Open Break

In [5639]:
final_predictions_both_present = final_predictions[(final_predictions['ViewData.Side0_UniqueIds'] !='nan') & (final_predictions['ViewData.Side1_UniqueIds']!='nan')]
final_predictions_side0_only = final_predictions[(final_predictions['ViewData.Side0_UniqueIds']!='nan') & (final_predictions['ViewData.Side1_UniqueIds'] =='nan')]
final_predictions_side1_only = final_predictions[(final_predictions['ViewData.Side0_UniqueIds']=='nan') & (final_predictions['ViewData.Side1_UniqueIds'] != 'nan')]
final_predictions_both_null = final_predictions[(final_predictions['ViewData.Side0_UniqueIds']=='nan') & (final_predictions['ViewData.Side1_UniqueIds']=='nan')]

In [5640]:
final_predictions_both_present.shape

(310, 13)

In [5641]:
aua_final = aua_final.drop_duplicates()
aua_final = aua_final.reset_index()
aua_final = aua_final.drop('index',1)

In [5642]:
final_predictions_both_present_aua_merge = pd.merge(final_predictions_both_present,aua_final, on=['ViewData.Side0_UniqueIds','ViewData.Side1_UniqueIds'], how='left' )
final_predictions_side0_only_aua_merge = pd.merge(final_predictions_side0_only,aua_final, on='ViewData.Side0_UniqueIds', how='left' )
final_predictions_side1_only_aua_merge = pd.merge(final_predictions_side1_only,aua_final, on='ViewData.Side1_UniqueIds', how='left' )

In [5643]:
#final_predictions_side1_only_aua_merge

In [5644]:
final_predictions_side0_only_aua_merge = final_predictions_side0_only_aua_merge.drop(['ViewData.BreakID_y', 'ViewData.Side1_UniqueIds_y', 'ViewData.Age_y'], 1)

final_predictions_side0_only_aua_merge = final_predictions_side0_only_aua_merge.rename(columns={'ViewData.BreakID_x': 'ViewData.BreakID'})
final_predictions_side0_only_aua_merge = final_predictions_side0_only_aua_merge.rename(columns={'ViewData.Side1_UniqueIds_x': 'ViewData.Side1_UniqueIds'})
final_predictions_side0_only_aua_merge = final_predictions_side0_only_aua_merge.rename(columns={'ViewData.Age_x': 'ViewData.Age'})


final_predictions_side1_only_aua_merge = final_predictions_side1_only_aua_merge.drop(['ViewData.BreakID_y', 'ViewData.Side0_UniqueIds_y', 'ViewData.Age_y'], 1)

final_predictions_side1_only_aua_merge = final_predictions_side1_only_aua_merge.rename(columns={'ViewData.BreakID_x': 'ViewData.BreakID'})
final_predictions_side1_only_aua_merge = final_predictions_side1_only_aua_merge.rename(columns={'ViewData.Side0_UniqueIds_x': 'ViewData.Side0_UniqueIds'})
final_predictions_side1_only_aua_merge = final_predictions_side1_only_aua_merge.rename(columns={'ViewData.Age_x': 'ViewData.Age'})



final_predictions_both_present_aua_merge = final_predictions_both_present_aua_merge.drop(['ViewData.BreakID_y', 'ViewData.Age_y'], 1)

final_predictions_both_present_aua_merge = final_predictions_both_present_aua_merge.rename(columns={'ViewData.BreakID_x': 'ViewData.BreakID'})
final_predictions_both_present_aua_merge = final_predictions_both_present_aua_merge.rename(columns={'ViewData.Age_x': 'ViewData.Age'})

In [5645]:
#final_prediction_show_cols = final_predictions_both_present_aua_merge.append([final_predictions_side0_only_aua_merge,final_predictions_side1_only_aua_merge])

In [5655]:
final11 = pd.concat([final_predictions_both_present_aua_merge, final_predictions_side0_only_aua_merge,final_predictions_side1_only_aua_merge], axis=0)

In [5656]:
final11 = final11.reset_index()
final11 = final11.drop('index',1)

In [5657]:
final12 = final11.drop_duplicates(['ViewData.BreakID', 'ViewData.Side1_UniqueIds','ViewData.Side0_UniqueIds', 'ViewData.Age'])

In [5658]:
final12.loc[(final12['Actual_Status']=='UCB'), 'ML_flag'] ='Non-ML'
final12.loc[(final12['Actual_Status']=='UCB'), 'Type'] = 'Closed Breaks'

In [5673]:
final12.loc[final12['Actual_Status']=='UCB','Predicted_Status'] = 'No-Prediction'

In [5674]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
print(classification_report(final12[final12['Type']=='One_to_One/Open']['Actual_Status'], final12[final12['Type']=='One_to_One/Open']['Predicted_Status']))

              precision    recall  f1-score   support

  Open Break       0.99      1.00      1.00       812
         UMB       0.00      0.00      0.00         9
         UMR       0.99      1.00      1.00       185
         UMT       0.94      1.00      0.97        66

    accuracy                           0.99      1072
   macro avg       0.73      0.75      0.74      1072
weighted avg       0.98      0.99      0.99      1072

In [5675]:
report = classification_report(final12[final12['Type']=='One_to_One/Open']['Actual_Status'], final12[final12['Type']=='One_to_One/Open']['Predicted_Status'], output_dict=True)
accuracy_table = pd.DataFrame(report).transpose()

In [5676]:
from sklearn.metrics import confusion_matrix
crosstab_table = pd.crosstab(final12[final12['Type']=='One_to_One/Open']['Actual_Status'], final12[final12['Type']=='One_to_One/Open']['Predicted_Status'])

In [5678]:
crosstab_table

Predicted_Status  Open Break  UMR  UMT
Actual_Status
Open Break               810    1    1
UMB                        6    0    3
UMR                        0  185    0
UMT                        0    0   66

## Save results

In [ ]:
final12.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/test2_show_cols.csv')

In [ ]:
accuracy_table.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/Accuracy_table_all_june.csv')

In [ ]:
crosstab_table.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/Crosstab_table_all_june.csv')

## Enitre month prediction

In [4747]:
all_june_data = pd.read_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/All_June_predictions_123.csv')

In [4694]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
print(classification_report(all_june_data[all_june_data['Type']=='One_to_One/Open']['Actual_Status'], all_june_data[all_june_data['Type']=='One_to_One/Open']['Predicted_Status']))

                   precision    recall  f1-score   support

       Open Break       0.97      0.99      0.98      9333
              UMB       1.00      0.16      0.27        32
UMB-Carry-Forward       1.00      1.00      1.00         1
              UMR       0.98      0.91      0.94      2711
              UMT       0.99      0.99      0.99       757

         accuracy                           0.97     12834
        macro avg       0.99      0.81      0.84     12834
     weighted avg       0.97      0.97      0.97     12834

In [4748]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
print(classification_report(all_june_data[all_june_data['Type']=='One_to_One/Open']['Actual_Status'], all_june_data[all_june_data['Type']=='One_to_One/Open']['Predicted_Status']))

              precision    recall  f1-score   support

  Open Break       1.00      1.00      1.00       167
         UMR       1.00      1.00      1.00       141
         UMT       1.00      1.00      1.00         2

    accuracy                           1.00       310
   macro avg       1.00      1.00      1.00       310
weighted avg       1.00      1.00      1.00       310

In [4695]:
report_all_june = classification_report(all_june_data[all_june_data['Type']=='One_to_One/Open']['Actual_Status'], all_june_data[all_june_data['Type']=='One_to_One/Open']['Predicted_Status'], output_dict=True)
accuracy_table_all_june = pd.DataFrame(report_all_june).transpose()

In [4696]:
accuracy_table_all_june

                   precision    recall  f1-score       support
Open Break          0.971716  0.993893  0.982679   9333.000000
UMB                 1.000000  0.156250  0.270270     32.000000
UMB-Carry-Forward   1.000000  1.000000  1.000000      1.000000
UMR                 0.978183  0.909627  0.942661   2711.000000
UMT                 0.986859  0.992074  0.989460    757.000000
accuracy            0.973897  0.973897  0.973897      0.973897
macro avg           0.987352  0.810369  0.837014  12834.000000
weighted avg        0.974048  0.973897  0.972851  12834.000000

In [4697]:
from sklearn.metrics import confusion_matrix
crosstab_all_june =  pd.crosstab(all_june_data[all_june_data['Type']=='One_to_One/Open']['Actual_Status'], all_june_data[all_june_data['Type']=='One_to_One/Open']['Predicted_Status'])

In [4698]:
crosstab_all_june

Predicted_Status   Open Break  UMB  UMB-Carry-Forward   UMR  UMT
Actual_Status
Open Break               9276    0                  0    55    2
UMB                        19    5                  0     0    8
UMB-Carry-Forward           0    0                  1     0    0
UMR                       245    0                  0  2466    0
UMT                         6    0                  0     0  751

## Save Results (Entire Month)

In [4702]:
accuracy_table_all_june.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/Accuracy_table_all_june.csv')

In [4703]:
crosstab_all_june.to_csv('//vitblrdevcons01/Raman  Strategy ML 2.0/All_Data/Weiss/JuneData/Final_Predictions/Crosstab_table_all_june.csv')